### ISSUE TITLE
貌似有一点小瑕疵。

### ISSUE THREAD

**Issue by boy-new-2019** [ifzhang/FairMOT#105]
首先很感谢您的工作。
其次在训练完您的代码后遇到一些小问题：
      1.貌似对行人的检测不够，经常无法检出远处静止的行人，我认为这是导致fn的一个重要因素，我准备着手在网络的深度和结构上进行修改，比如额外的为检测分支增加一些特征提取层，为跟踪分支增加一个额外的上采样，您看是否可行？
      2.我在mot20等的跟踪评价该怎么评估？我运行track.py后貌似只有FP，是不是因为没有gt数据？但是我不知道为什么无法完成mot challenge的注册，那是不是就无法完成跟踪的其他指标评价？
     3. 如果想将该模型改为对车辆的跟踪，是不是只要将数据集改为车辆的就可以了？

**Comment by ifzhang** [comment]
1. I think it is a general problem in detection task that small objects are difficult to detect. The ways you proposed may help get better results.
2. You can only get a MOT Challenge account and you can test the results of MOT20.
3. Yes. The network structure can be the same and only change dataset if you just want to track cars.

**Comment by boy-new-2019** [comment]
> 1. I think it is a general problem in detection task that small objects are difficult to detect. The ways you proposed may help get better results.
> 2. You can only get a MOT Challenge account and you can test the results of MOT20.
> 3. Yes. The network structure can be the same and only change dataset if you just want to track cars.

thank you for your help。
After using the VPN, I successfully applied for a MOT Challenge account.
Thank you again for your help and wish you good health and success in your research.
