### ISSUE TITLE
无法达到MOT17的精度

### ISSUE THREAD

**Issue by BRANDONeras** [ifzhang/FairMOT#108]
我利用了你的原始代码和原始的数据集训练出来的模型，在MOT17上的测试结果比原文结果大概低了1%，测了两次都是这样，请问你是用了什么特别的训练方法吗？

**Comment by ifzhang** [comment]
I used batchsize 12 for dla34 model and trained for 30 epochs on the original dataset and finetuned it on MOT17 for 10 epochs. The finetuning gets about 0.2+ MOTA. Maybe it is the batchsize that effects the results. I will change it to 12 in the experiment sh file.

**Comment by BRANDONeras** [comment]
> I used batchsize 12 for dla34 model and trained for 30 epochs on the original dataset and finetuned it on MOT17 for 10 epochs. The finetuning gets about 0.2+ MOTA. Maybe it is the batchsize that effects the results. I will change it to 12 in the experiment sh file.

感谢，我会尝试一下的

**Comment by BRANDONeras** [comment]
> I used batchsize 12 for dla34 model and trained for 30 epochs on the original dataset and finetuned it on MOT17 for 10 epochs. The finetuning gets about 0.2+ MOTA. Maybe it is the batchsize that effects the results. I will change it to 12 in the experiment sh file.

你好，我想再问一下，除了batch的大小，训练里面你还用了其他特殊的训练方法吗？

**Comment by ifzhang** [comment]
No other tricks.

**Comment by BRANDONeras** [comment]
> No other tricks.

好的，谢谢回复

**Comment by State226** [comment]
没有在额外的数据集上训练过吗
