### ISSUE TITLE
About the Re-ID part

### ISSUE THREAD

**Issue by XnetDA** [ifzhang/FairMOT#109]
Hi, sorry for bothering you. I have two minor questions for the re-id part.
1. in the /src/train/mot/py,  line 64,            
 if opt.id_weight > 0:               
                id_head = _tranpose_and_gather_feat(output['id'], batch['ind'])
                id_head = id_head[batch['reg_mask'] > 0].contiguous()   

here, the output seem to be [12, 512, 152, 272] which should be N*C*W*H, but after the .gather, it changes to [12, 152*272, 512] to [12, 128, 512],  can I understand as here you only get the first 128 points from the "batch"?

2. Should I understand the detection and re-id as 2-stage process? first you get the center location of bbox by hm head, then use the center location to get feature for re-id?

Hope for your kind guidance,

best regards

**Comment by ifzhang** [comment]
1. The parameter batch['ind'] decides the 128 points, it contains all ground truth center locations and add zeros to make it a max number of 128. 
2. During training, we use gt center locations to get reid features. During testing, we use the center location estimated by the heatmap head to get reid features. It is just a post processing way and I do not think it is a two-stage way because the network is just one-stage.

**Comment by XnetDA** [comment]
Thank you so much for your quick reply. It perfectly solved my problem. I still have another two minor questions about the method.
1. I want to make sure in the re-Id head, should every identity(like Person-1, Person-2, etc) be treated as a class, or the class in re-Id part means ‘person’, ‘background’ etc?(I guess the former)
2. In the testing phase, for the online part, do you mean the tested frames will be used to update the classifier for Re-ID head? And may I assume that the Re-ID part in the testing is quite different from the training part? As in the testing it seems you further add Kalman filter to do prediction, and also identity linking(association). These two modules do not exist in the training right? Hope for your kind guidance.

Best regards

**Comment by ifzhang** [comment]
1. The former.
2. During testing, we do not use the id classifier. We just extract the reid features using the center point and then perform identity linking based on cosine similarity.

**Comment by XnetDA** [comment]
Got it, thank you! If so, may I ask how the kalman filter works in the training/testing? The linking is just based on the cos distance among center points in neighboring frames right? 

Best regards,

**Comment by XnetDA** [comment]
Also, I want to ask some about for the occlusion cases(like one identity lost for 3 frames and then appear), and a new identity that newly appear in one of middle frames, should we also keep some “memories” for each lost/deleted identity just like deepsort?

**Comment by ifzhang** [comment]
We just use kalman filter in testing. Kalman filter prevents linking between objects which are far away from each other. The linking is mainly performed by calculating the reid similarity. We keep the tracklets for 30 frames similar to deepsort.

**Comment by XnetDA** [comment]
Thank you! I think I can understand the algorithm quite well now. Btw, may I ask how to understand the meaning of “online” in re-ID?

**Comment by ifzhang** [comment]
Online means we only use information of the current frame and the past frames, not the future frames.

**Comment by XnetDA** [comment]
totoally got you. Thanks! Helped me a lot.
