### ISSUE TITLE
Problem about multi-Class multi-object tracking 

### ISSUE THREAD

**Issue by CaptainEven** [ifzhang/FairMOT#131]
Hi, I have successfully modified FairMOT to train and detect multi-class and multi-object, but when it comes about tracking updates, a problem occurs:
    Different class objects track ids linked together, that is to say, a person's track id starts with the max track id of previous class car(e.g 15) rather than 1. So, how to modify this, i 'm a new commer of tracking, here is my main code:

    def update(self, im_blob, img0):
        self.frame_id += 1

        activated_starcks_dict = defaultdict(list)
        refind_stracks_dict = defaultdict(list)
        lost_stracks_dict = defaultdict(list)
        removed_stracks_dict = defaultdict(list)
        output_stracks_dict = defaultdict(list)

        width = img0.shape[1]
        height = img0.shape[0]
        inp_height = im_blob.shape[2]
        inp_width = im_blob.shape[3]

        c = np.array([width / 2., height / 2.], dtype=np.float32)
        s = max(float(inp_width) / float(inp_height) * height, width) * 1.0
        meta = {'c': c,
                's': s,
                'out_height': inp_height // self.opt.down_ratio,
                'out_width': inp_width // self.opt.down_ratio}

        ''' Step 1: Network forward, get detections & embeddings'''
        with torch.no_grad():  
            output = self.model.forward(im_blob)[-1]

            hm = output['hm'].sigmoid_()
            # print("hm shape ", hm.shape, "hm:\n", hm)

            wh = output['wh']
            # print("wh shape ", wh.shape, "wh:\n", wh)

            id_feature = output['id']
            id_feature = F.normalize(id_feature, dim=1)

            reg = output['reg'] if self.opt.reg_offset else None
            # print("reg shape ", reg.shape, "reg:\n", reg)

            dets, inds, cls_inds_mask = mot_decode(heatmap=hm,
                                                   wh=wh,
                                                   reg=reg,
                                                   num_classes=self.opt.num_classes,
                                                   cat_spec_wh=self.opt.cat_spec_wh,
                                                   K=self.opt.K)

            # id_feature = _tranpose_and_gather_feat(id_feature, inds)
            # id_feature = id_feature.squeeze(0)  # K × FeatDim
            # id_feature = id_feature.cpu().numpy()

            # ----- 
            cls_id_feats = []  
            for cls_id in range(self.opt.num_classes): 
                cls_inds = inds[:, cls_inds_mask[cls_id]]

                cls_id_feature = _tranpose_and_gather_feat(id_feature, cls_inds)  # inds: 1×128
                cls_id_feature = cls_id_feature.squeeze(0)  # n × FeatDim
                cls_id_feature = cls_id_feature.cpu().numpy() 
                cls_id_feats.append(cls_id_feature)

        dets = self.post_process(dets, meta)
        dets = self.merge_outputs([dets])
        # dets = self.merge_outputs(dets)[1]

        for cls_id in range(self.opt.num_classes):  # cls_id starts with 0
            cls_dets = dets[cls_id + 1]

            '''
            for i in range(0, cls_dets.shape[0]):
                bbox = cls_dets[i][0:4]
                cv2.rectangle(img0,
                              (bbox[0], bbox[1]),  # left-top point
                              (bbox[2], bbox[3]),  # right-down point
                              [0, 255, 255],  # yellow
                              2)
                cv2.putText(img0,
                            id2cls[cls_id],
                            (bbox[0], bbox[1]),
                            cv2.FONT_HERSHEY_PLAIN,
                            1.3,
                            [0, 0, 255],  # red
                            2)
            cv2.imshow('{}'.format(id2cls[cls_id]), img0)
            cv2.waitKey(0)
            '''

            remain_inds = cls_dets[:, 4] > self.opt.conf_thres
            cls_dets = cls_dets[remain_inds]
            cls_id_feature = cls_id_feats[cls_id][remain_inds]

            if len(cls_dets) > 0:
                '''Detections, tlbrs: top left bottom right score'''
                cls_detections = [STrack(STrack.tlbr_to_tlwh(tlbrs[:4]), tlbrs[4], feat, buff_size=30)
                                  for (tlbrs, feat) in zip(cls_dets[:, :5], cls_id_feature)]
            else:
                cls_detections = []

            ''' Add newly detected tracklets to tracked_stracks'''
            unconfirmed_dict = defaultdict(list)
            tracked_stracks_dict = defaultdict(list)  # type: key(cls_id), value: list[STrack]
            for track in self.tracked_stracks_dict[cls_id]:
                if not track.is_activated:
                    unconfirmed_dict[cls_id].append(track)
                else:
                    tracked_stracks_dict[cls_id].append(track)

            ''' Step 2: First association, with embedding'''
            strack_pool_dict = defaultdict(list)
            strack_pool_dict[cls_id] = joint_stracks(tracked_stracks_dict[cls_id], self.lost_stracks_dict[cls_id])

            # Predict the current location with KF
            # for strack in strack_pool:
            STrack.multi_predict(strack_pool_dict[cls_id])
            dists = matching.embedding_distance(strack_pool_dict[cls_id], cls_detections)
            dists = matching.fuse_motion(self.kalman_filter, dists, strack_pool_dict[cls_id], cls_detections)
            matches, u_track, u_detection = matching.linear_assignment(dists, thresh=0.7)

            for i_tracked, i_det in matches:
                track = strack_pool_dict[cls_id][i_tracked]
                det = cls_detections[i_det]
                if track.state == TrackState.Tracked:
                    track.update(cls_detections[i_det], self.frame_id)
                    activated_starcks_dict[cls_id].append(track)  # for multi-class
                else:
                    track.re_activate(det, self.frame_id, new_id=False)
                    refind_stracks_dict[cls_id].append(track)

            ''' Step 3: Second association, with IOU'''
            cls_detections = [cls_detections[i] for i in u_detection]
            r_tracked_stracks = [strack_pool_dict[cls_id][i]
                                 for i in u_track if strack_pool_dict[cls_id][i].state == TrackState.Tracked]
            dists = matching.iou_distance(r_tracked_stracks, cls_detections)
            matches, u_track, u_detection = matching.linear_assignment(dists, thresh=0.5)

            for i_tracked, i_det in matches:
                track = r_tracked_stracks[i_tracked]
                det = cls_detections[i_det]
                if track.state == TrackState.Tracked:
                    track.update(det, self.frame_id)
                    activated_starcks_dict[cls_id].append(track)
                else:
                    track.re_activate(det, self.frame_id, new_id=False)
                    refind_stracks_dict[cls_id].append(track)

            for it in u_track:
                track = r_tracked_stracks[it]
                if not track.state == TrackState.Lost:
                    track.mark_lost()
                    lost_stracks_dict[cls_id].append(track)

            '''Deal with unconfirmed tracks, usually tracks with only one beginning frame'''
            cls_detections = [cls_detections[i] for i in u_detection]
            dists = matching.iou_distance(unconfirmed_dict[cls_id], cls_detections)
            matches, u_unconfirmed, u_detection = matching.linear_assignment(dists, thresh=0.7)
            for i_tracked, i_det in matches:
                unconfirmed_dict[cls_id][i_tracked].update(cls_detections[i_det], self.frame_id)
                activated_starcks_dict[cls_id].append(unconfirmed_dict[cls_id][i_tracked])
            for it in u_unconfirmed:
                track = unconfirmed_dict[cls_id][it]
                track.mark_removed()
                removed_stracks_dict[cls_id].append(track)

            """ Step 4: Init new stracks"""
            for i_new in u_detection:
                track = cls_detections[i_new]
                if track.score < self.det_thresh:
                    continue
                track.activate(self.kalman_filter, self.frame_id)
                activated_starcks_dict[cls_id].append(track)

            """ Step 5: Update state"""
            for track in self.lost_stracks_dict[cls_id]:
                if self.frame_id - track.end_frame > self.max_time_lost:
                    track.mark_removed()
                    removed_stracks_dict[cls_id].append(track)

            # print('Ramained match {} s'.format(t4-t3))
            self.tracked_stracks_dict[cls_id] = [t for t in self.tracked_stracks_dict[cls_id] if
                                                 t.state == TrackState.Tracked]
            self.tracked_stracks_dict[cls_id] = joint_stracks(self.tracked_stracks_dict[cls_id],
                                                              activated_starcks_dict[cls_id])
            self.tracked_stracks_dict[cls_id] = joint_stracks(self.tracked_stracks_dict[cls_id],
                                                              refind_stracks_dict[cls_id])
            self.lost_stracks_dict[cls_id] = sub_stracks(self.lost_stracks_dict[cls_id],
                                                         self.tracked_stracks_dict[cls_id])
            self.lost_stracks_dict[cls_id].extend(lost_stracks_dict[cls_id])
            self.lost_stracks_dict[cls_id] = sub_stracks(self.lost_stracks_dict[cls_id],
                                                         self.removed_stracks_dict[cls_id])
            self.removed_stracks_dict[cls_id].extend(removed_stracks_dict[cls_id])
            self.tracked_stracks_dict[cls_id], self.lost_stracks_dict[cls_id] = remove_duplicate_stracks(
                self.tracked_stracks_dict[cls_id],
                self.lost_stracks_dict[cls_id])

            # get scores of lost tracks
            output_stracks_dict[cls_id] = [track for track in self.tracked_stracks_dict[cls_id] if track.is_activated]

            logger.debug('===========Frame {}=========='.format(self.frame_id))
            logger.debug('Activated: {}'.format(
                [track.track_id for track in activated_starcks_dict[cls_id]]))
            logger.debug('Refind: {}'.format(
                [track.track_id for track in refind_stracks_dict[cls_id]]))
            logger.debug('Lost: {}'.format(
                [track.track_id for track in lost_stracks_dict[cls_id]]))
            logger.debug('Removed: {}'.format(
                [track.track_id for track in removed_stracks_dict[cls_id]]))

        return output_stracks_dict

**Comment by CaptainEven** [comment]
![Frame 3_screenshot_09 06 2020_bicycle](https://user-images.githubusercontent.com/9303747/84096060-77e87b00-aa33-11ea-9cd6-2f2b94f0066d.png)
![Frame 3_screenshot_09 06 2020_car](https://user-images.githubusercontent.com/9303747/84096075-7e76f280-aa33-11ea-849d-a30d56ea9f2a.png)
![Uploading Frame 3_screenshot_09.06.2020_person.png…]()

**Comment by CaptainEven** [comment]
![Frame 3_screenshot_09 06 2020_person](https://user-images.githubusercontent.com/9303747/84096331-47551100-aa34-11ea-9d72-41200e7d5c26.png)

**Comment by CaptainEven** [comment]
@ifzhang I have solved the problem by reset track id(_count) to 0 when parsing tracking info every new object class.

**Comment by CaptainEven** [comment]
![result2](https://user-images.githubusercontent.com/9303747/84132715-c835fc00-aa78-11ea-90de-d45b80f4cce6.gif)

**Comment by ifzhang** [comment]
Wow, that's cool! Hope you can update your code!

**Comment by JayLIU0911** [comment]
> Hi, I have successfully modified FairMOT to train and detect multi-class and multi-object, but when it comes about tracking updates, a problem occurs:
> Different class objects track ids linked together, that is to say, a person's track id starts with the max track id of previous class car(e.g 15) rather than 1. So, how to modify this, i 'm a new commer of tracking, here is my main code:
> 
> ```
> def update(self, im_blob, img0):
>     self.frame_id += 1
> 
>     activated_starcks_dict = defaultdict(list)
>     refind_stracks_dict = defaultdict(list)
>     lost_stracks_dict = defaultdict(list)
>     removed_stracks_dict = defaultdict(list)
>     output_stracks_dict = defaultdict(list)
> 
>     width = img0.shape[1]
>     height = img0.shape[0]
>     inp_height = im_blob.shape[2]
>     inp_width = im_blob.shape[3]
> 
>     c = np.array([width / 2., height / 2.], dtype=np.float32)
>     s = max(float(inp_width) / float(inp_height) * height, width) * 1.0
>     meta = {'c': c,
>             's': s,
>             'out_height': inp_height // self.opt.down_ratio,
>             'out_width': inp_width // self.opt.down_ratio}
> 
>     ''' Step 1: Network forward, get detections & embeddings'''
>     with torch.no_grad():  
>         output = self.model.forward(im_blob)[-1]
> 
>         hm = output['hm'].sigmoid_()
>         # print("hm shape ", hm.shape, "hm:\n", hm)
> 
>         wh = output['wh']
>         # print("wh shape ", wh.shape, "wh:\n", wh)
> 
>         id_feature = output['id']
>         id_feature = F.normalize(id_feature, dim=1)
> 
>         reg = output['reg'] if self.opt.reg_offset else None
>         # print("reg shape ", reg.shape, "reg:\n", reg)
> 
>         dets, inds, cls_inds_mask = mot_decode(heatmap=hm,
>                                                wh=wh,
>                                                reg=reg,
>                                                num_classes=self.opt.num_classes,
>                                                cat_spec_wh=self.opt.cat_spec_wh,
>                                                K=self.opt.K)
> 
>         # id_feature = _tranpose_and_gather_feat(id_feature, inds)
>         # id_feature = id_feature.squeeze(0)  # K × FeatDim
>         # id_feature = id_feature.cpu().numpy()
> 
>         # ----- 
>         cls_id_feats = []  
>         for cls_id in range(self.opt.num_classes): 
>             cls_inds = inds[:, cls_inds_mask[cls_id]]
> 
>             cls_id_feature = _tranpose_and_gather_feat(id_feature, cls_inds)  # inds: 1×128
>             cls_id_feature = cls_id_feature.squeeze(0)  # n × FeatDim
>             cls_id_feature = cls_id_feature.cpu().numpy() 
>             cls_id_feats.append(cls_id_feature)
> 
>     dets = self.post_process(dets, meta)
>     dets = self.merge_outputs([dets])
>     # dets = self.merge_outputs(dets)[1]
> 
>     for cls_id in range(self.opt.num_classes):  # cls_id starts with 0
>         cls_dets = dets[cls_id + 1]
> 
>         '''
>         for i in range(0, cls_dets.shape[0]):
>             bbox = cls_dets[i][0:4]
>             cv2.rectangle(img0,
>                           (bbox[0], bbox[1]),  # left-top point
>                           (bbox[2], bbox[3]),  # right-down point
>                           [0, 255, 255],  # yellow
>                           2)
>             cv2.putText(img0,
>                         id2cls[cls_id],
>                         (bbox[0], bbox[1]),
>                         cv2.FONT_HERSHEY_PLAIN,
>                         1.3,
>                         [0, 0, 255],  # red
>                         2)
>         cv2.imshow('{}'.format(id2cls[cls_id]), img0)
>         cv2.waitKey(0)
>         '''
> 
>         remain_inds = cls_dets[:, 4] > self.opt.conf_thres
>         cls_dets = cls_dets[remain_inds]
>         cls_id_feature = cls_id_feats[cls_id][remain_inds]
> 
>         if len(cls_dets) > 0:
>             '''Detections, tlbrs: top left bottom right score'''
>             cls_detections = [STrack(STrack.tlbr_to_tlwh(tlbrs[:4]), tlbrs[4], feat, buff_size=30)
>                               for (tlbrs, feat) in zip(cls_dets[:, :5], cls_id_feature)]
>         else:
>             cls_detections = []
> 
>         ''' Add newly detected tracklets to tracked_stracks'''
>         unconfirmed_dict = defaultdict(list)
>         tracked_stracks_dict = defaultdict(list)  # type: key(cls_id), value: list[STrack]
>         for track in self.tracked_stracks_dict[cls_id]:
>             if not track.is_activated:
>                 unconfirmed_dict[cls_id].append(track)
>             else:
>                 tracked_stracks_dict[cls_id].append(track)
> 
>         ''' Step 2: First association, with embedding'''
>         strack_pool_dict = defaultdict(list)
>         strack_pool_dict[cls_id] = joint_stracks(tracked_stracks_dict[cls_id], self.lost_stracks_dict[cls_id])
> 
>         # Predict the current location with KF
>         # for strack in strack_pool:
>         STrack.multi_predict(strack_pool_dict[cls_id])
>         dists = matching.embedding_distance(strack_pool_dict[cls_id], cls_detections)
>         dists = matching.fuse_motion(self.kalman_filter, dists, strack_pool_dict[cls_id], cls_detections)
>         matches, u_track, u_detection = matching.linear_assignment(dists, thresh=0.7)
> 
>         for i_tracked, i_det in matches:
>             track = strack_pool_dict[cls_id][i_tracked]
>             det = cls_detections[i_det]
>             if track.state == TrackState.Tracked:
>                 track.update(cls_detections[i_det], self.frame_id)
>                 activated_starcks_dict[cls_id].append(track)  # for multi-class
>             else:
>                 track.re_activate(det, self.frame_id, new_id=False)
>                 refind_stracks_dict[cls_id].append(track)
> 
>         ''' Step 3: Second association, with IOU'''
>         cls_detections = [cls_detections[i] for i in u_detection]
>         r_tracked_stracks = [strack_pool_dict[cls_id][i]
>                              for i in u_track if strack_pool_dict[cls_id][i].state == TrackState.Tracked]
>         dists = matching.iou_distance(r_tracked_stracks, cls_detections)
>         matches, u_track, u_detection = matching.linear_assignment(dists, thresh=0.5)
> 
>         for i_tracked, i_det in matches:
>             track = r_tracked_stracks[i_tracked]
>             det = cls_detections[i_det]
>             if track.state == TrackState.Tracked:
>                 track.update(det, self.frame_id)
>                 activated_starcks_dict[cls_id].append(track)
>             else:
>                 track.re_activate(det, self.frame_id, new_id=False)
>                 refind_stracks_dict[cls_id].append(track)
> 
>         for it in u_track:
>             track = r_tracked_stracks[it]
>             if not track.state == TrackState.Lost:
>                 track.mark_lost()
>                 lost_stracks_dict[cls_id].append(track)
> 
>         '''Deal with unconfirmed tracks, usually tracks with only one beginning frame'''
>         cls_detections = [cls_detections[i] for i in u_detection]
>         dists = matching.iou_distance(unconfirmed_dict[cls_id], cls_detections)
>         matches, u_unconfirmed, u_detection = matching.linear_assignment(dists, thresh=0.7)
>         for i_tracked, i_det in matches:
>             unconfirmed_dict[cls_id][i_tracked].update(cls_detections[i_det], self.frame_id)
>             activated_starcks_dict[cls_id].append(unconfirmed_dict[cls_id][i_tracked])
>         for it in u_unconfirmed:
>             track = unconfirmed_dict[cls_id][it]
>             track.mark_removed()
>             removed_stracks_dict[cls_id].append(track)
> 
>         """ Step 4: Init new stracks"""
>         for i_new in u_detection:
>             track = cls_detections[i_new]
>             if track.score < self.det_thresh:
>                 continue
>             track.activate(self.kalman_filter, self.frame_id)
>             activated_starcks_dict[cls_id].append(track)
> 
>         """ Step 5: Update state"""
>         for track in self.lost_stracks_dict[cls_id]:
>             if self.frame_id - track.end_frame > self.max_time_lost:
>                 track.mark_removed()
>                 removed_stracks_dict[cls_id].append(track)
> 
>         # print('Ramained match {} s'.format(t4-t3))
>         self.tracked_stracks_dict[cls_id] = [t for t in self.tracked_stracks_dict[cls_id] if
>                                              t.state == TrackState.Tracked]
>         self.tracked_stracks_dict[cls_id] = joint_stracks(self.tracked_stracks_dict[cls_id],
>                                                           activated_starcks_dict[cls_id])
>         self.tracked_stracks_dict[cls_id] = joint_stracks(self.tracked_stracks_dict[cls_id],
>                                                           refind_stracks_dict[cls_id])
>         self.lost_stracks_dict[cls_id] = sub_stracks(self.lost_stracks_dict[cls_id],
>                                                      self.tracked_stracks_dict[cls_id])
>         self.lost_stracks_dict[cls_id].extend(lost_stracks_dict[cls_id])
>         self.lost_stracks_dict[cls_id] = sub_stracks(self.lost_stracks_dict[cls_id],
>                                                      self.removed_stracks_dict[cls_id])
>         self.removed_stracks_dict[cls_id].extend(removed_stracks_dict[cls_id])
>         self.tracked_stracks_dict[cls_id], self.lost_stracks_dict[cls_id] = remove_duplicate_stracks(
>             self.tracked_stracks_dict[cls_id],
>             self.lost_stracks_dict[cls_id])
> 
>         # get scores of lost tracks
>         output_stracks_dict[cls_id] = [track for track in self.tracked_stracks_dict[cls_id] if track.is_activated]
> 
>         logger.debug('===========Frame {}=========='.format(self.frame_id))
>         logger.debug('Activated: {}'.format(
>             [track.track_id for track in activated_starcks_dict[cls_id]]))
>         logger.debug('Refind: {}'.format(
>             [track.track_id for track in refind_stracks_dict[cls_id]]))
>         logger.debug('Lost: {}'.format(
>             [track.track_id for track in lost_stracks_dict[cls_id]]))
>         logger.debug('Removed: {}'.format(
>             [track.track_id for track in removed_stracks_dict[cls_id]]))
> 
>     return output_stracks_dict
> ```

Hi CaptainEven,

I am very interested in your extension work. May I know more details about your work? I would like to talk to you in private if possible.

Ji

**Comment by CaptainEven** [comment]
@JayLIU0911 @ifzhang I have made the MCMOT repo public, you guys can refer to https://github.com/CaptainEven/MCMOT

**Comment by ifzhang** [comment]
Great work!

**Comment by JayLIU0911** [comment]
Cool! Thank you!

**Comment by JAYCHOU2020** [comment]
> Hi, I have successfully modified FairMOT to train and detect multi-class and multi-object, but when it comes about tracking updates, a problem occurs:
> Different class objects track ids linked together, that is to say, a person's track id starts with the max track id of previous class car(e.g 15) rather than 1. So, how to modify this, i 'm a new commer of tracking, here is my main code:
> 
> ```
> def update(self, im_blob, img0):
>     self.frame_id += 1
> 
>     activated_starcks_dict = defaultdict(list)
>     refind_stracks_dict = defaultdict(list)
>     lost_stracks_dict = defaultdict(list)
>     removed_stracks_dict = defaultdict(list)
>     output_stracks_dict = defaultdict(list)
> 
>     width = img0.shape[1]
>     height = img0.shape[0]
>     inp_height = im_blob.shape[2]
>     inp_width = im_blob.shape[3]
> 
>     c = np.array([width / 2., height / 2.], dtype=np.float32)
>     s = max(float(inp_width) / float(inp_height) * height, width) * 1.0
>     meta = {'c': c,
>             's': s,
>             'out_height': inp_height // self.opt.down_ratio,
>             'out_width': inp_width // self.opt.down_ratio}
> 
>     ''' Step 1: Network forward, get detections & embeddings'''
>     with torch.no_grad():  
>         output = self.model.forward(im_blob)[-1]
> 
>         hm = output['hm'].sigmoid_()
>         # print("hm shape ", hm.shape, "hm:\n", hm)
> 
>         wh = output['wh']
>         # print("wh shape ", wh.shape, "wh:\n", wh)
> 
>         id_feature = output['id']
>         id_feature = F.normalize(id_feature, dim=1)
> 
>         reg = output['reg'] if self.opt.reg_offset else None
>         # print("reg shape ", reg.shape, "reg:\n", reg)
> 
>         dets, inds, cls_inds_mask = mot_decode(heatmap=hm,
>                                                wh=wh,
>                                                reg=reg,
>                                                num_classes=self.opt.num_classes,
>                                                cat_spec_wh=self.opt.cat_spec_wh,
>                                                K=self.opt.K)
> 
>         # id_feature = _tranpose_and_gather_feat(id_feature, inds)
>         # id_feature = id_feature.squeeze(0)  # K × FeatDim
>         # id_feature = id_feature.cpu().numpy()
> 
>         # ----- 
>         cls_id_feats = []  
>         for cls_id in range(self.opt.num_classes): 
>             cls_inds = inds[:, cls_inds_mask[cls_id]]
> 
>             cls_id_feature = _tranpose_and_gather_feat(id_feature, cls_inds)  # inds: 1×128
>             cls_id_feature = cls_id_feature.squeeze(0)  # n × FeatDim
>             cls_id_feature = cls_id_feature.cpu().numpy() 
>             cls_id_feats.append(cls_id_feature)
> 
>     dets = self.post_process(dets, meta)
>     dets = self.merge_outputs([dets])
>     # dets = self.merge_outputs(dets)[1]
> 
>     for cls_id in range(self.opt.num_classes):  # cls_id starts with 0
>         cls_dets = dets[cls_id + 1]
> 
>         '''
>         for i in range(0, cls_dets.shape[0]):
>             bbox = cls_dets[i][0:4]
>             cv2.rectangle(img0,
>                           (bbox[0], bbox[1]),  # left-top point
>                           (bbox[2], bbox[3]),  # right-down point
>                           [0, 255, 255],  # yellow
>                           2)
>             cv2.putText(img0,
>                         id2cls[cls_id],
>                         (bbox[0], bbox[1]),
>                         cv2.FONT_HERSHEY_PLAIN,
>                         1.3,
>                         [0, 0, 255],  # red
>                         2)
>         cv2.imshow('{}'.format(id2cls[cls_id]), img0)
>         cv2.waitKey(0)
>         '''
> 
>         remain_inds = cls_dets[:, 4] > self.opt.conf_thres
>         cls_dets = cls_dets[remain_inds]
>         cls_id_feature = cls_id_feats[cls_id][remain_inds]
> 
>         if len(cls_dets) > 0:
>             '''Detections, tlbrs: top left bottom right score'''
>             cls_detections = [STrack(STrack.tlbr_to_tlwh(tlbrs[:4]), tlbrs[4], feat, buff_size=30)
>                               for (tlbrs, feat) in zip(cls_dets[:, :5], cls_id_feature)]
>         else:
>             cls_detections = []
> 
>         ''' Add newly detected tracklets to tracked_stracks'''
>         unconfirmed_dict = defaultdict(list)
>         tracked_stracks_dict = defaultdict(list)  # type: key(cls_id), value: list[STrack]
>         for track in self.tracked_stracks_dict[cls_id]:
>             if not track.is_activated:
>                 unconfirmed_dict[cls_id].append(track)
>             else:
>                 tracked_stracks_dict[cls_id].append(track)
> 
>         ''' Step 2: First association, with embedding'''
>         strack_pool_dict = defaultdict(list)
>         strack_pool_dict[cls_id] = joint_stracks(tracked_stracks_dict[cls_id], self.lost_stracks_dict[cls_id])
> 
>         # Predict the current location with KF
>         # for strack in strack_pool:
>         STrack.multi_predict(strack_pool_dict[cls_id])
>         dists = matching.embedding_distance(strack_pool_dict[cls_id], cls_detections)
>         dists = matching.fuse_motion(self.kalman_filter, dists, strack_pool_dict[cls_id], cls_detections)
>         matches, u_track, u_detection = matching.linear_assignment(dists, thresh=0.7)
> 
>         for i_tracked, i_det in matches:
>             track = strack_pool_dict[cls_id][i_tracked]
>             det = cls_detections[i_det]
>             if track.state == TrackState.Tracked:
>                 track.update(cls_detections[i_det], self.frame_id)
>                 activated_starcks_dict[cls_id].append(track)  # for multi-class
>             else:
>                 track.re_activate(det, self.frame_id, new_id=False)
>                 refind_stracks_dict[cls_id].append(track)
> 
>         ''' Step 3: Second association, with IOU'''
>         cls_detections = [cls_detections[i] for i in u_detection]
>         r_tracked_stracks = [strack_pool_dict[cls_id][i]
>                              for i in u_track if strack_pool_dict[cls_id][i].state == TrackState.Tracked]
>         dists = matching.iou_distance(r_tracked_stracks, cls_detections)
>         matches, u_track, u_detection = matching.linear_assignment(dists, thresh=0.5)
> 
>         for i_tracked, i_det in matches:
>             track = r_tracked_stracks[i_tracked]
>             det = cls_detections[i_det]
>             if track.state == TrackState.Tracked:
>                 track.update(det, self.frame_id)
>                 activated_starcks_dict[cls_id].append(track)
>             else:
>                 track.re_activate(det, self.frame_id, new_id=False)
>                 refind_stracks_dict[cls_id].append(track)
> 
>         for it in u_track:
>             track = r_tracked_stracks[it]
>             if not track.state == TrackState.Lost:
>                 track.mark_lost()
>                 lost_stracks_dict[cls_id].append(track)
> 
>         '''Deal with unconfirmed tracks, usually tracks with only one beginning frame'''
>         cls_detections = [cls_detections[i] for i in u_detection]
>         dists = matching.iou_distance(unconfirmed_dict[cls_id], cls_detections)
>         matches, u_unconfirmed, u_detection = matching.linear_assignment(dists, thresh=0.7)
>         for i_tracked, i_det in matches:
>             unconfirmed_dict[cls_id][i_tracked].update(cls_detections[i_det], self.frame_id)
>             activated_starcks_dict[cls_id].append(unconfirmed_dict[cls_id][i_tracked])
>         for it in u_unconfirmed:
>             track = unconfirmed_dict[cls_id][it]
>             track.mark_removed()
>             removed_stracks_dict[cls_id].append(track)
> 
>         """ Step 4: Init new stracks"""
>         for i_new in u_detection:
>             track = cls_detections[i_new]
>             if track.score < self.det_thresh:
>                 continue
>             track.activate(self.kalman_filter, self.frame_id)
>             activated_starcks_dict[cls_id].append(track)
> 
>         """ Step 5: Update state"""
>         for track in self.lost_stracks_dict[cls_id]:
>             if self.frame_id - track.end_frame > self.max_time_lost:
>                 track.mark_removed()
>                 removed_stracks_dict[cls_id].append(track)
> 
>         # print('Ramained match {} s'.format(t4-t3))
>         self.tracked_stracks_dict[cls_id] = [t for t in self.tracked_stracks_dict[cls_id] if
>                                              t.state == TrackState.Tracked]
>         self.tracked_stracks_dict[cls_id] = joint_stracks(self.tracked_stracks_dict[cls_id],
>                                                           activated_starcks_dict[cls_id])
>         self.tracked_stracks_dict[cls_id] = joint_stracks(self.tracked_stracks_dict[cls_id],
>                                                           refind_stracks_dict[cls_id])
>         self.lost_stracks_dict[cls_id] = sub_stracks(self.lost_stracks_dict[cls_id],
>                                                      self.tracked_stracks_dict[cls_id])
>         self.lost_stracks_dict[cls_id].extend(lost_stracks_dict[cls_id])
>         self.lost_stracks_dict[cls_id] = sub_stracks(self.lost_stracks_dict[cls_id],
>                                                      self.removed_stracks_dict[cls_id])
>         self.removed_stracks_dict[cls_id].extend(removed_stracks_dict[cls_id])
>         self.tracked_stracks_dict[cls_id], self.lost_stracks_dict[cls_id] = remove_duplicate_stracks(
>             self.tracked_stracks_dict[cls_id],
>             self.lost_stracks_dict[cls_id])
> 
>         # get scores of lost tracks
>         output_stracks_dict[cls_id] = [track for track in self.tracked_stracks_dict[cls_id] if track.is_activated]
> 
>         logger.debug('===========Frame {}=========='.format(self.frame_id))
>         logger.debug('Activated: {}'.format(
>             [track.track_id for track in activated_starcks_dict[cls_id]]))
>         logger.debug('Refind: {}'.format(
>             [track.track_id for track in refind_stracks_dict[cls_id]]))
>         logger.debug('Lost: {}'.format(
>             [track.track_id for track in lost_stracks_dict[cls_id]]))
>         logger.debug('Removed: {}'.format(
>             [track.track_id for track in removed_stracks_dict[cls_id]]))
> 
>     return output_stracks_dict
> ```

really thanks
