### ISSUE TITLE
hm_gauss vs hm_weight

### ISSUE THREAD

**Issue by caseyhong** [ifzhang/FairMOT#132]
Curious about this line `radius = self.opt.hm_gauss if self.opt.mse_loss else radius` in dataset/jde.py - It looks like hm_gauss is not set as an option (but there is one named hm_weight). Are they equivalent/is this a typo? Thanks!

**Comment by ifzhang** [comment]
The radious should be input_size / 128, about 8. However, the MSE loss seems not working for FairMOT and you can just ignore it.
