### ISSUE TITLE
GPU compatibility DCNv2_new not out the box

### ISSUE THREAD

**Issue by FlorentijnD** [ifzhang/FairMOT#137]
Following just the steps in the repo, I found that building DCNv2 does not work on my machine which has a NVIDIA Tesla K80 x.

The exact error I have when running 
`cd src
python track.py mot --load_model ../models/all_dla34.pth --conf_thres 0.6` 
is :
`RuntimeError: Not compiled with GPU support (dcn_v2_forward at /{FAIRMOT_PATH}/src/lib/models/networks/DCNv2_new/src/dcn_v2.h:35)`

**Comment by FlorentijnD** [comment]
Problem solved - had to do with GPU itself

**Comment by zfs1993** [comment]
i have same problem,what does you mean 'had to do with GPU itself'?

**Comment by Huqingrui** [comment]
you need to install cuda and cudnn on the system, and install cudatoolkit on python?
that's the reason of my problem.

**Comment by zfs1993** [comment]
i had installed py3.7_cuda9.2.148_cudnn7.6.2_0 , cudatoolkit   9.2, cuda 9.2.148,cudnn7602,but it still failed,does it mean i have to intall cuda10?

**Comment by Ursanon** [comment]
@Huqingrui @zfs1993 

Make sure that you have CUDA Toolkit from [official docs](https://developer.nvidia.com/cuda-downloads)

You can verify installation with:

```python
import torch
from torch.utils.cpp_extension import CUDA_HOME

cuda_available = torch.cuda.is_available()

is_installation_ok = cuda_available and CUDA_HOME is not None

print('Is CUDA OK: {0}\nIs cuda available: {1}\nCuda home: {2}'.format(
    is_installation_ok, cuda_available, CUDA_HOME))

```

**Comment by Huqingrui** [comment]
yeah, use CUDA_HOME to verify the cuda

**Comment by zfs1993** [comment]
> @Huqingrui @zfs1993
> 
> Make sure that you have CUDA Toolkit from [official docs](https://developer.nvidia.com/cuda-downloads)
> 
> You can verify installation with:
> 
> ```python
> import torch
> from torch.utils.cpp_extension import CUDA_HOME
> 
> cuda_available = torch.cuda.is_available()
> 
> is_installation_ok = cuda_available and CUDA_HOME is not None
> 
> print('Is CUDA OK: {0}\nIs cuda available: {1}\nCuda home: {2}'.format(
>     is_installation_ok, cuda_available, CUDA_HOME))
> ```


> (py37) root@ume-PowerEdge-T630:/opt/app/OCR/zhang/fairmot/FairMOT-master/src# python testcuda.py 
Is CUDA OK: True
Is cuda available: True
Cuda home: /opt/app/OCR/zhang/software/cuda92

this is the result of your code ,it seems cuda works well，it really confuse me

**Comment by Ursanon** [comment]
Did you compile DCNv2 with make.sh ?

**Comment by zfs1993** [comment]
> Did you compile DCNv2 with make.sh ?

yes ,i did. it has some error.
i run the testcuda.py.with this error,
RuntimeError: Backward is not reentrant, i.e., running backward with same input and grad_output multiple times gives different values, although analytical gradient matches numerical gradient,
i cant solve it , i am trying to update the cudatoolkit9.2 to cudatoolkit10 ,maybe it will be solved
