### ISSUE TITLE
Triplet Loss

### ISSUE THREAD

**Issue by danielzgsilva** [ifzhang/FairMOT#141]
I notice that there are some comments in the code regarding triplet loss. Did you attempt to leverage triplet loss at some point? If so, how did it fare when compared to CE and why did you choose to not leave it in?

Thanks in advance

**Comment by ifzhang** [comment]
If you want to use triplet loss, you need to sample the training batch to make it contains both positive samples and negative samples. It can be used together with CE loss.

**Comment by chenrxi** [comment]
how can I sample the training batch to get better performance?
