### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by Thunzhsh** [ifzhang/FairMOT#143]
When I run the setup.py, a problem has occured:
/content/drive/My Drive/Colab Notebooks/FairMOT-master/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(86): error: identifier "THCState_getCurrentStream" is undefined

/content/drive/My Drive/Colab Notebooks/FairMOT-master/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(182): error: identifier "THCState_getCurrentStream" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_0000058f_00000000-6_dcn_v2_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

It seems the required header file which includes THCState_getCurrentStream is not included.
I searched but no solution is found. Could you please help me?

**Comment by NaifahNurya** [comment]
You can refer to the following issue, maybe it could be helpful

https://github.com/ifzhang/FairMOT/issues/86


https://github.com/ifzhang/FairMOT/issues/69

**Comment by Thunzhsh** [comment]
> You can refer to the following issue, maybe it could be helpful
> 
> #86
> 
> #69

Solved.
Thank you very much !

**Comment by mainguyenanhvu** [comment]
I have read both issues, but I couldn't find the way to overcome them. Please give me some guide. Thank you very much.
