### ISSUE TITLE
Some error happened during training

### ISSUE THREAD

**Issue by supyer9** [ifzhang/FairMOT#149]
In the process of my training data, an error occurred when the first epoch was about to end.
The error content is:
RuntimeError: invalid argument 2: non-empty vector or matrix expected at /pytorch/aten/src/THCUNN/assNLLCriterion.cu:31
The code is located in mot.py:
id_loss += self.IDLoss(id_output, id_target)
What is the cause of this and how can I solve this problem.
Thanks.

**Comment by NaifahNurya** [comment]
Have a look on this issue:
https://github.com/ifzhang/FairMOT/issues/49

**Comment by supyer9** [comment]
OK, Thank you!
