### ISSUE TITLE
How can I dispaly the confidence of the detected person?

### ISSUE THREAD

**Issue by DJever23** [ifzhang/FairMOT#15]
Hi,
        Could you tell me how to print the confidence of the detected person?  I want to write it to the result.txt file.
         Thank you!

**Comment by ifzhang** [comment]
In src/track.py eval_seq(), like line 67, you can set the 'confidence = t.score' and then write the confidence in the results txt file by changing some code in eval_seq() and write_results().

**Comment by DJever23** [comment]
OK,It worked.Thanks a lot!
