### ISSUE TITLE
Can you provide other indicator data on the MOT test set?

### ISSUE THREAD

**Issue by JoJoliking** [ifzhang/FairMOT#151]
I want to compare all the indicators of your test set in the paper, just like those given on the MOT official website

**Comment by ifzhang** [comment]
You can check the performance of FairMOT on the MOT official website:
https://motchallenge.net/method/MOT=3015&chl=10

**Comment by JoJoliking** [comment]
Thank you so much for your help. And the new results are higher than the theory. I am Looking forward to your outstanding work
your sincerely
JoJo
