### ISSUE TITLE
Extracting Re-id features

### ISSUE THREAD

**Issue by CaucMark** [ifzhang/FairMOT#156]
Hi, thanks for your excellent work!
Here's my question. I want to make some changes on Identity Embedding Branch, such as changing the way to extract the Re-id features. But I can't find the identity embedding branch in the code you provided(forgive me, I'm new in computer vision field). Would you please tell me where can I modify the code?

**Comment by ifzhang** [comment]
The channel of the embedding branch is set here:
https://github.com/ifzhang/FairMOT/blob/ca78d3f01d1953c3d72ee8b01f24a5ddec2689c3/src/lib/opts.py#L217
The code of the network is here:
https://github.com/ifzhang/FairMOT/blob/ca78d3f01d1953c3d72ee8b01f24a5ddec2689c3/src/lib/models/networks/pose_dla_dcn.py#L445
