### ISSUE TITLE
Will the MOTA change for DLA-34 and HRNetV2-18 on same dataset ?

### ISSUE THREAD

**Issue by dpsdev14091998** [ifzhang/FairMOT#157]

**Comment by ifzhang** [comment]
Yes, it will change. The MOTA is affected by the training model and testing parameters.

**Comment by apekshapriya** [comment]
Hey @ifzhang 
Which one is usually better on a human-based dataset?

**Comment by ifzhang** [comment]
@apekshapriya I test them on the test set of MOT17 dataset and find DLA-34 has better results. The deformable convolution in DLA-34 plays an important role. HRNet-W18 has better performance on small objects.

**Comment by apekshapriya** [comment]
@ifzhang  Thanks!
