### ISSUE TITLE
Can we change the font size of the numbers(person number) that we are getting in the ouput video??

### ISSUE THREAD

**Issue by dpsdev14091998** [ifzhang/FairMOT#160]

**Comment by ifzhang** [comment]
You can change it here:
https://github.com/ifzhang/FairMOT/blob/ca78d3f01d1953c3d72ee8b01f24a5ddec2689c3/src/lib/tracking_utils/visualization.py#L34

**Comment by dpsdev14091998** [comment]
Thank you so much.
Closing the issue.
