### ISSUE TITLE
Error while unzipping

### ISSUE THREAD

**Issue by xs020420** [ifzhang/FairMOT#165]
Hi! When I unzip the zip file of the code, an error  occurs on /asset/MOT17.gif . Could you give some suggestion on solving the problem?

**Comment by ifzhang** [comment]
I'm not sure why it happens, but no worry about that. We don't use asset folder to run the code. I just put some jps and demo gif in it to show on github.

**Comment by xs020420** [comment]
Thanks for reply! I got it!
