### ISSUE TITLE
Do you have the code for processing MOT17 annotations from the original data format?

### ISSUE THREAD

**Issue by danielzgsilva** [ifzhang/FairMOT#170]
When downloading the MOT17 dataset directly from JDE's google drive link I find that the zip file was not compressed properly. Therefore, I've downloaded MOT17 from the official website but am unsure how to generate the labels_with_id folder. Do you have code for generating labels for MOT17, similar to the scripts you've provided for MOT15 and MOT20?

Thank you for all your help.

**Comment by danielzgsilva** [comment]
It was trivial to adjust and use the gen_labels_20 script for generating MOT17 annotations. Do you see any issues with doing this? 
One thing I noticed is that in the gen_labels_15 script you first sort the gt.txt file before looping through it. Is there a particular reason this is done for MOT15 and not MOT20?

![image](https://user-images.githubusercontent.com/43020082/86309360-8caacf80-bbe9-11ea-9042-645437ed9ae7.png)



Thanks again in advance.

**Comment by ifzhang** [comment]
I think it is quite similar to MOT20 but different from MOT15. The gt file of MOT15 labels each person of one frame, like 
frame1, id1, 
frame1, id2, 
frame1, id3...
But MOT17 and MOT20 labels the same person in different frames, like
frame1, id1,
frame2, id1,
frame3, id1
You can find the code to process MOT17 here:
https://github.com/Zhongdao/Towards-Realtime-MOT/issues/61

**Comment by danielzgsilva** [comment]
Ah I see, I noticed that as well. Thanks for the quick reply, I should be good to go.
