### ISSUE TITLE
Question about overfitting on human pose

### ISSUE THREAD

**Issue by xs020420** [ifzhang/FairMOT#178]
Hi! Thanks for good job on id re-identification! I have a question about the model's abilitity of detecting human which is not in walking pose. 
When I test the detection part on human who is sitting or bending，the detection score is extremely low (0~0.2)。I guess the reason is that most human pose in 6 dataset which are used in training is walking pose。
Does it work if I train the detection part  on COCO(just class human) and remain Re-ID branch? I ‘m not sure if the origin Re-ID branch is also suitable for human which is not walking(pedestrians).

**Comment by ifzhang** [comment]
Yes, you can train it on COCO like Cityperson and ETHZ which do not have id labels. You can set the id label -1 and the CE Loss will ignore it and only the detection part is trained. The reid branch may not perform well on sitting person but it may still work on some easy cases.

**Comment by xs020420** [comment]
Thx for suggestion! I will try the experiment on COCO later.
