### ISSUE TITLE
Multitask learning with uncertainty ?

### ISSUE THREAD

**Issue by kakusikun** [ifzhang/FairMOT#19]
[Here](https://github.com/ifzhang/FairMOT/blob/2fc491918a67393de93eefb65f4b1d32cd2d03b7/src/lib/trains/mot.py#L76), it looks like that the uncertainty is used to learn multitask.

BUT, I can NOT find that the parameters is updated by any optimizer ...
I just found that the instance of loss is made [here](https://github.com/ifzhang/FairMOT/blob/2fc491918a67393de93eefb65f4b1d32cd2d03b7/src/lib/trains/base_trainer.py#L29).

Could you point out where the uncertainty is learned during training?

**Comment by ifzhang** [comment]
We set the parameters here: https://github.com/ifzhang/FairMOT/blob/12f50ca8821d7d3ecbebea8afdf673e421ebba32/src/lib/trains/mot.py#L35

**Comment by kakusikun** [comment]
Thanks for your quick reply.
I know the uncertainty is set as a parameter.
But it needs to be added to the optimizer to be updated not just make it a parameter.
Still the question, where it is updated.

**Comment by ifzhang** [comment]
I use the parameters in the loss below: https://github.com/ifzhang/FairMOT/blob/4cdb3499a80d5de3bda79d6a4e43db5878570bbf/src/lib/trains/mot.py#L76

**Comment by kakusikun** [comment]
I mean something like https://github.com/ifzhang/FairMOT/blob/4cdb3499a80d5de3bda79d6a4e43db5878570bbf/src/train.py#L44

**Comment by ifzhang** [comment]
Thank you very much for your question! I have added the parameters to optimizer and fixed the bug.

**Comment by whut2962575697** [comment]
I found that you added a new param_group in the optimizer, so the optimizer will fail when it is resumed

**Comment by whut2962575697** [comment]
maybe you should change the position of resume code

**Comment by ifzhang** [comment]
Thanks, I will fix the bug.
