### ISSUE TITLE
How much FPS do you get with which configuration?

### ISSUE THREAD

**Issue by faruknane** [ifzhang/FairMOT#199]
Hi, I am getting 4.34 frames per second with:
- gpu, gtx 1050ti
- cpu, i7 7700hq
- platform, Windows 10
- Model name, "all_dla34.pth"

How much fps do you get it with a stronger GPU? 
Can anyone share me the details? Thanks.

![image](https://user-images.githubusercontent.com/37745467/88061707-8a94ba80-cb70-11ea-86a4-0dc914ed47c1.png)

**Comment by ifzhang** [comment]
I run the experiments on RTX 2080 Ti GPU. The network inference time is about 31 ms per frame and the tracking/association time is about 1ms for 6 person. The overall FPS is about 25-30 depending on how many people in the frame.

**Comment by faruknane** [comment]
> I run the experiments on RTX 2080 Ti GPU. The network inference time is about 31 ms per frame and the tracking/association time is about 1ms for 6 person. The overall FPS is about 25-30 depending on how many people in the frame. 

I created 2-3 threads for video streaming, AI model, processing output of the model and tracking system. I ran these threads in parallel. If the model takes 31ms then it means we can get 60fps. It is super good news. Thank you so much for the effort you put for this.
