### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by wyh1992-NJ** [ifzhang/FairMOT#20]
win10
I have installed all the requirements. 
When I input "python F:\soft\FairMOT-master\src\demo.py ",there are following errors:
ModuleNotFoundError: No module named '_ext';

So I input" python F:\soft\FairMOT-master\src\lib\models\networks\DCNv2\setup.py build develop",there are also some errors.The errors are as follows:
c:\users\admin\anaconda3\lib\site-packages\torch\include\pybind11\detail/common.h(71): fatal error C1189: #error:  pybind11 requires MSVC 2015 update 3 or newer
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2.
I hope to get some guidance,thank you very much.

**Comment by zubairahmed-ai** [comment]
See my issue https://github.com/ifzhang/FairMOT/issues/5 basically get the latest version of the code, download HRNet models and comment a few lines and it should work, I struggled alot on this myself

**Comment by ifzhang** [comment]
Sadly it is difficult to build DCNv2 on Windows. You can use HRNet which do not use DCNv2 to run the demo code following the instructions in readme. You can also turn to issue #5 for help when running HRNet.

**Comment by zubairahmed-ai** [comment]
Haha...I beat you to it @ifzhang

**Comment by FLyingLSJ** [comment]
run this code may be can fix this probelm.
`pip install --upgrade cython`

**Comment by wyh1992-NJ** [comment]
Thank you all,now I have only one question left,the problems are as follows:
F:\FairMOT-master\FairMOT\src>python demo.py mot --load_model ../models/all_hrnet_v2_w18.pth --input-video ../videos/mot16-03.mp4 --output-root ../results --arch hrnet_w18 --reid_dim 128 --conf_thres 0.4 --arch hrnet_18
Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  F:\FairMOT-master\FairMOT\src\lib\..\..\exp\mot\default
heads {'hm': 1, 'wh': 2, 'id': 128, 'reg': 2}
2020-04-17 17:30:01 [INFO]: Starting tracking...
Lenth of the video: 1500 frames
Creating model...
=> please download pre-trained models first!
2020-04-17 17:30:01 [INFO]: ../models/hrnetv2_w18_imagenet_pretrained.pth is not exist!
'ffmpeg' 不是内部或外部命令，也不是可运行的程序
I have changed the hrnet_w18.yaml:
 #PRETRAINED: '../models/hrnetv2_w18_imagenet_pretrained.pth'
  #PRETRAINED: '../models/hrnetv2_w32_imagenet_pretrained.pth'
  PRETRAINED: '../models/hrnetv2_w18_imagenet_pretrained.pth'
and I have  downloaded the hrnetv2_w18_imagenet_pretrained.pth and the hrnetv2_w32_imagenet_pretrained.pth py python ,and I put the files in the models.

<img width="383" alt="img" src="https://user-images.githubusercontent.com/46039305/79554987-78b6fd80-80d1-11ea-88cf-8ac438e71c8a.PNG">
 I doubt that the file I have downloaded is wrong,please give me some suggestion, Thank you very much!

**Comment by ifzhang** [comment]
Oh, I see! You should put all the models in $FAIRMOT_ROOT$/models instead of  $FAIRMOT_ROOT$/src/lib/models.

**Comment by wyh1992-NJ** [comment]
I have successfully run this model, thank you very much!
