### ISSUE TITLE
[Question] Why multi-scale training strategy(like yolov3/v4) not applied in this repo?

### ISSUE THREAD

**Issue by CaptainEven** [ifzhang/FairMOT#200]

**Comment by ifzhang** [comment]
I think multi-scale training strategy can help get better results. I plan to add it in the future.

**Comment by CaptainEven** [comment]
Thanks for replying!

**Comment by CaptainEven** [comment]
@ifzhang Hi, I have add multi-scale training in the extention repo: https://github.com/CaptainEven/MCMOT, the effectiveness has not been tested yet.

**Comment by CaptainEven** [comment]
![image](https://user-images.githubusercontent.com/9303747/91160397-f03e0e80-e6fb-11ea-87fd-4f78a81946c3.png)

**Comment by CaptainEven** [comment]
![image](https://user-images.githubusercontent.com/9303747/91160519-12d02780-e6fc-11ea-8dde-04ea0335ba50.png)

**Comment by ShellyLingling** [comment]
> @ifzhang Hi, I have add multi-scale training in the extention repo: https://github.com/CaptainEven/MCMOT, the effectiveness has not been tested yet.

@CaptainEven  Wow, you're amazing！ May I ask how the improvements are working out?
