### ISSUE TITLE
Pytorch XLA/TPU Support 

### ISSUE THREAD

**Issue by hardik0** [ifzhang/FairMOT#203]
## Questions and Help
Thank you for your great repo. I was just wondering if you had TPU support for this accelerated training scheme or on the roadmap for the future. 
After changing quite a lot in several functions (mainly on train.py, mot.py and base_trainer.py) I am not able to surpass an apparently .backward hang and I think I am going to default to GPUs for now. I am trying with [xla ](https://github.com/pytorch/xla)and [pytorch-lightning](https://github.com/PytorchLightning/pytorch-lightning)

**Comment by ifzhang** [comment]
Glad to see your effort to make the repo supported on other platforms! Sorry that I haven't planned to add TPU support now. Maybe I will try it in the future.
