### ISSUE TITLE
cannot reach 58.7 MOTA on MOT20 test set with 'mot20_dla34.pth'.

### ISSUE THREAD

**Issue by fandulu** [ifzhang/FairMOT#204]
Could I ask a question? I try to download mot20_dla34.pth, and run
python track.py mot --test_mot20 True --load_model ../models/mot20_dla34.pth --reid_dim 128 --conf_thres 0.3 --K 500
 but cannot reach 58.7 MOTA on MOT20 test set.
The main reason is the recall is quite low.
Could you please give some suggestions?

**Comment by ifzhang** [comment]
It seems you are using hrnet model which was not trained on MOT20.
You can use :
python track.py mot --load_model ../models/mot20_dla34.pth --reid_dim 128 --conf_thres 0.3 --test_mot20 True
to get the MOT20 test txt results.
I think I have updated the model of the 58.7 MOTA on MOT20 test set.

**Comment by fandulu** [comment]
I am sorry, I put the wrong weight in my question, I do use mot20_dla34.pth other than all_hrnet_v2_w18.pth. The recall is 23.8, compared with Fairmot 82.8,  it is quite low. By inspecting the video, I found that many boxes are missing.

**Comment by ifzhang** [comment]
Sorry, I forget to add --K 500 and --conf_thres 0.3 to the command. I think adding these two opts will make it right. --K means the max number of people in one frame and the default is 128 which causes the low recall.

**Comment by fandulu** [comment]
Got it, solved. thanks very much for your help!

**Comment by PLester** [comment]
@ifzhang Could you please provide the newest model for MOT20? Thank u very much!
