### ISSUE TITLE
Re identification branch

### ISSUE THREAD

**Issue by eltonsst** [ifzhang/FairMOT#212]
Dear Author,

I'm new on the computer vision field and I would like to extract the part of the code that does the re-identification but I can't find it. Can you please tell me where I can find the code?

**Comment by ifzhang** [comment]
https://github.com/ifzhang/FairMOT/blob/2a353b16a591bf997aadd5d24b73e599672906c4/src/lib/models/networks/pose_dla_dcn.py#L445
