### ISSUE TITLE
re-id loss is larger when I resume training

### ISSUE THREAD

**Issue by rujiewu** [ifzhang/FairMOT#214]
Hi @ifzhang, Thanks for sharing the great work that you have done! I feel a little confused here.

When I tried training to 20th epoch, the id loss is only 0.6031.
But when I resume training, the losses of detection are all normal, and the re-id loss becomes 8.7542. It's so Higher!

**Comment by ifzhang** [comment]
Maybe it is because the parameters of the id classifier in the loss part is not resumed.

**Comment by rujiewu** [comment]
> Maybe it is because the parameters of the id classifier in the loss part is not resumed.

Thank you for your response so fast. I set resume and imported model_20.pth correctly. The loss of detection works well. 
What else will I need to do for the parameters of the id classifier resume?

**Comment by ifzhang** [comment]
Sadly it is because I do not save the parameters of id_classifier during training.

**Comment by rujiewu** [comment]
> Sadly it is because I do not save the parameters of id_classifier during training.

Got it, thanks very much for your help!

**Comment by PLester** [comment]
@rujiewu @ifzhang  Do you know how to solve this problem?
