### ISSUE TITLE
questions about test_det.py

### ISSUE THREAD

**Issue by LrobotD** [ifzhang/FairMOT#221]
Thanks for your nice work,i have trained my dataset and i am learning the test_det.py for getting my own test results,but i have two questions as follows:
1、Could you please tell me why the result of  my custom dataset 'p' is so small when other evaluation criteria is normal.
================================================================================
      Image      Total          P          R        mAP
          4       4231          0          0          0       1.12s
        164       4231      0.019      0.577      0.444      0.193s
        324       4231     0.0166      0.444      0.348      0.195s
        484       4231     0.0255      0.542      0.427      0.195s
        644       4231     0.0281      0.577      0.454      0.196s
        804       4231     0.0276      0.585      0.448      0.196s
        964       4231     0.0299      0.609       0.48      0.196s
       1124       4231     0.0324      0.651      0.538      0.197s
       1284       4231     0.0308      0.664       0.56      0.197s
       1444       4231     0.0298      0.701      0.606      0.198s
       1604       4231     0.0304      0.727      0.639      0.197s
       1764       4231     0.0298      0.742      0.659      0.198s
       1924       4231     0.0289      0.755      0.679      0.198s
       2084       4231     0.0282      0.769      0.693      0.196s
       2244       4231     0.0269      0.767      0.697      0.197s
       2404       4231     0.0268       0.78      0.713      0.197s
       2564       4231     0.0276      0.788      0.725      0.198s
       2724       4231     0.0273      0.796      0.736      0.198s
       2884       4231     0.0282      0.804      0.747      0.198s
       3044       4231     0.0282      0.811      0.756      0.198s
       3204       4231     0.0285      0.818      0.765      0.198s
       3364       4231     0.0284      0.823      0.772      0.199s
       3524       4231     0.0282      0.829       0.78      0.198s
       3684       4231     0.0274      0.834      0.786      0.206s
       3844       4231      0.027      0.841      0.793      0.199s
       4004       4231     0.0266      0.847        0.8      0.197s
       4164       4231     0.0259      0.846      0.794      0.215s
      Image      Total          P          R        mAP
AP: 0.7957
Should i change some parameters？THANKS.
2、How to debug through the line'output = model(imgs.cuda())[-1]',when i debug this code,maybe the program is loading a large model,and the 'watch variables' just show me nothing , cause i can't debug next lines,do you have some suggestions about this problem except 'print'? Please forgive me for being a novice.
Thanks for you wonderful work and looking forwards to your reply!

**Comment by ifzhang** [comment]
1. In this part, we use all the detections to evaluate mAP and do not use thresh to filter the detections. So the precision is low. The mAP metric is normal.
2. You can debug in the model file:
https://github.com/ifzhang/FairMOT/blob/master/src/lib/models/networks/pose_dla_dcn.py

**Comment by LrobotD** [comment]
Thanks for replying!Than's make sense. And thanks for you nice work again.
