### ISSUE TITLE
How about supporting objects other than People?

### ISSUE THREAD

**Issue by zubairahmed-ai** [ifzhang/FairMOT#23]
I tried it on a Traffic video but I got the same `ffmpeg` error that I received in my earlier issue https://github.com/ifzhang/FairMOT/issues/5 so I presume other objects are not yet supported, any plans?

**Comment by ifzhang** [comment]
It needs other training dataset and some modifications on the network structure in 'hm_head'. I have no plans for that recently. Thanks.

**Comment by zubairahmed-ai** [comment]
Thanks for the video output please look at this comment and reach out to me on email https://github.com/ifzhang/FairMOT/issues/5#issuecomment-613403590 and also what's your LinkedIn @ifzhang  I was just searching for you there but couldn't find? I need to give credit to you for something I'm making
