### ISSUE TITLE
关键更新

### ISSUE THREAD

**Issue by noneUmbrella** [ifzhang/FairMOT#233]
您好，我注意到当前的FairMOT代码相比一个月前有了重要的更新，并且在各个MOT数据集上也有了显著地提升。请问是否可以列举一下几条重要的，对结果影响较大的更新部分？

**Comment by ifzhang** [comment]
We notice that the MOT Challenge dataset has bounding boxes out of the image. We make some revision in the data processing part and make FairMOT able to detect boxes out of the image and the results improve a lot.

**Comment by noneUmbrella** [comment]
Does "bounding boxes out of the image" means that part of the bounding box of a target out of the image, other than the whole bounding box out of the image? In addition, do you make this revision in training or test, or both of them?

**Comment by noneUmbrella** [comment]
Does "bounding boxes out of the image" means that part of the bounding box of a target out of the image, other than the whole bounding box out of the image? In addition, do you make this revision in training or test, or both of them?@ifzhang

**Comment by ifzhang** [comment]
It means part of the bounding box of a target is out of the image. We keep center of the box inside the image, so it is the real center of the box and we set left, top, right and bottom to get the box instead of width and height. We make the revision in both training and test.

**Comment by noneUmbrella** [comment]
Thank you for your excellent work.@ifzhang
