### ISSUE TITLE
Error when nID is 1

### ISSUE THREAD

**Issue by astrayne** [ifzhang/FairMOT#241]
I made a simple toy dataset for training which has only one person in a video.
When I start training I got an error like below.
ValueError: math domain error
---> 34         self.emb_scale = math.sqrt(2) * math.log(self.nID - 1)
How can I avoid this error when nID is 1?

**Comment by ifzhang** [comment]
You can just not use the emb_scale for the embedding.

**Comment by astrayne** [comment]
Thanks!

**Comment by xiexu666** [comment]
@astrayne Hello, I have some questions about nID parameter.  When train on custom dataset，how to change this paramter?
