### ISSUE TITLE
After Training Multi-Class and Multi-Object model, can't use demo.py

### ISSUE THREAD

**Issue by shan-ying** [ifzhang/FairMOT#252]
This is the great work! Thank you for it! :)

I have a question about the Multi-Class and Multi-Object.
I trained the model use the multi-class, the step include set the class number is 5 in opt (In opt.txt "num_classes: 5") and change the dataset's class id.

Now I finished training, want to predict my video, but has this error.
![image](https://user-images.githubusercontent.com/18310015/94401401-1f351d80-019d-11eb-807a-c879d2794560.png)

I can't find the problem, could you help me to fix this problem?
Thank you :)

**Comment by ifzhang** [comment]
During tracking, each class should be separately computed. 
A multi-class FairMOT repo can be found here: https://github.com/CaptainEven/MCMOT
Hope that can help you!
