### ISSUE TITLE
Error while executing ./make.sh

### ISSUE THREAD

**Issue by arvindchandel** [ifzhang/FairMOT#253]
git clone https://github.com/CharlesShang/DCNv2
cd DCNv2
./make.sh

Gives error below:

compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by arvindchandel** [comment]
Got the solution.

**Comment by dwchen-tech** [comment]
> Got the solution.

how to solve this error? i met the similar error msg:
error: command '/usr/local/cuda:/usr/local/cuda/bin/nvcc' failed with exit status 1
