### ISSUE TITLE
How to speed up execution?

### ISSUE THREAD

**Issue by egorsmkv** [ifzhang/FairMOT#27]
I have successfully ran the demo script and made the example used in the README file by myself.
But the speed is slow, it's around 2-3 FPS.

How can I speed up this number?

**Comment by BrainlessDylan** [comment]
What GPU?

**Comment by BrainlessDylan** [comment]
Running fine on my gtx 760 and on my RTX Titan

**Comment by egorsmkv** [comment]
It can’t check it at the moment but it’s PCI-E GeForce GT1030 2GB DDR5 MSI if I’m not wrong.
