### ISSUE TITLE
CUDA out of memory, fine-tuning on MOT15 on Google Colab

### ISSUE THREAD

**Issue by Ravsehajsinghpuri** [ifzhang/FairMOT#270]
When I am trying to run the experiment for fine-tuning FairMOT model on the 2DMOT2015 dataset on Google Colab, I get the follow error **RuntimeError: CUDA out of memory. Tried to allocate 106.00 MiB (GPU 0; 7.43 GiB total capacity; 6.75 GiB already allocated; 42.88 MiB free; 6.87 GiB reserved in total by PyTorch)**
I also tried setting the batch_size to 6, still it throws the same error. Google Colab uses Tesla K80 GPU with 12 GB ram. I wonder why this much memory is causing a problem.
@ifzhang Please try to solve this issue or give your comments on this so that it is easier for me to take my research forward without delay.
Thanks in advance.

**Comment by ifzhang** [comment]
You can reduce the batchsize when finetuning on MOT15, such as 4 or 2.

**Comment by yuehui130** [comment]
@ifzhang  When I reduce the batch size to 2, it still has errors. 
`RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 3.00 GiB total capacity; 1.97 GiB already allocated; 102.40 KiB free; 89.85 MiB cached) (malloc at ..\c10\cuda\CUDACachingAllocator.cpp:267)
`
Could you tell me how to solve it?
Sorry, @you again.

**Comment by yuehui130** [comment]
And，Does the terminal display nothing during training?
![image](https://user-images.githubusercontent.com/57430945/101887089-bd068900-3bdf-11eb-8fb6-2355bcec3007.png)

Is this normal?

**Comment by Ravsehajsinghpuri** [comment]
@yuehui130 I have tried the same on google Colab which has Tesla K80 with limited Ram to 12GB. It didn't work. I think you will have to use a larger GPU for training this model. Also, reducing the batch size to 1 still doesn't solve the problem. 
Moreover, during training, it should display logs in your terminal.
