### ISSUE TITLE
怎么测试MOT指标？

### ISSUE THREAD

**Issue by yumeng88** [ifzhang/FairMOT#271]
error：
2020-11-02 16:24:05 [INFO]: Time elapsed: 309.56 seconds, FPS: 18.68
                IDF1  IDP  IDR Rcll Prcn GT MT PT ML    FP FN IDs  FM  MOTA MOTP IDt IDa IDm
ADL-Rundle-1    0.0% 0.0% nan% nan% 0.0%  0  0  0  0  6614  0   0   0 -inf%  nan   0   0   0
ADL-Rundle-3    0.0% 0.0% nan% nan% 0.0%  0  0  0  0  7264  0   0   0 -inf%  nan   0   0   0
AVG-TownCentre  0.0% 0.0% nan% nan% 0.0%  0  0  0  0  5816  0   0   0 -inf%  nan   0   0   0
ETH-Crossing    0.0% 0.0% nan% nan% 0.0%  0  0  0  0   737  0   0   0 -inf%  nan   0   0   0
ETH-Jelmoli     0.0% 0.0% nan% nan% 0.0%  0  0  0  0  2462  0   0   0 -inf%  nan   0   0   0
ETH-Linthescher 0.0% 0.0% nan% nan% 0.0%  0  0  0  0  7050  0   0   0 -inf%  nan   0   0   0
KITTI-16        0.0% 0.0% nan% nan% 0.0%  0  0  0  0  1312  0   0   0 -inf%  nan   0   0   0
KITTI-19        0.0% 0.0% nan% nan% 0.0%  0  0  0  0  4227  0   0   0 -inf%  nan   0   0   0
PETS09-S2L2     0.0% 0.0% nan% nan% 0.0%  0  0  0  0  7496  0   0   0 -inf%  nan   0   0   0
TUD-Crossing    0.0% 0.0% nan% nan% 0.0%  0  0  0  0  1023  0   0   0 -inf%  nan   0   0   0
Venice-1        0.0% 0.0% nan% nan% 0.0%  0  0  0  0  2754  0   0   0 -inf%  nan   0   0   0
OVERALL         0.0% 0.0% nan% nan% 0.0%  0  0  0  0 46755  0   0   0 -inf%  nan   0   0   0
想问一下MOT15 16 17年的数据集下 test文件夹里面的groundtruth在哪里获取？或者这个指标怎么进行测试？感谢！

**Comment by Gaoxinyue423** [comment]
I have the same problem. How did you solve it?

**Comment by irfanfadhullah** [comment]
Hello, can you share how to solve this problem?
