### ISSUE TITLE
Possible bug in flip augmentation

### ISSUE THREAD

**Issue by austinmw** [ifzhang/FairMOT#279]
Hi, when the image is flipped along the x-axis, the labels are modified by:
```python
 labels[:, 2] = 1 - labels[:, 2] 
```
Since at this point the labels are in `xywh` format, this maintains the width which is correct, but I believe the new x1 value then needs to be shifted by the width as (1-x-w) instead of (1-x), or:

```python
labels[:, 2] = 1 - (labels[:, 2] + labels[:, 4])
```

Does this make sense or am I misunderstanding this operation?

**Comment by developer0hye** [comment]
The original one is correct.

**Comment by austinmw** [comment]
@developer0hye Can you explain? To flip a box along the x-axis, if you simply change the X1 position to (1-X1), then the box can extend off the image. 

Example:

[X, Y, W, H] = [0.1, 0.5, 0.2, 0.2]
So originally the box is between [0.1, 0.3] on the X axis.
First flip method: 1-0.1=0.9 --> [0.9, 0.5, 0.2, 0.2], Now X extends from 0.9 to 1.1, going outside of the box.
Second flip method --> 1-0.1-0.2=0.7 --> [0.7, 0.5, 0.2, 0.2], Now box coords are [0.7, 0.9] and properly flipped.

I drew out the images and bbox labels in tensorboard and they align with objects in the second example, but not in the original.

**Comment by developer0hye** [comment]
@austinmw 

If x is top left corner, you are right.
But, x is center point, isn't it??

**Comment by austinmw** [comment]
@developer0hye Ah you're right! 
I attempted to draw my boxes in tensorboard by converting (x_center,y_center,w,h) to (x1,y1,x2,y2), so mistakenly thought there was an issue. Thank you!

**Comment by developer0hye** [comment]
@austinmw 
I love the way for you to analyze the code completely!
