### ISSUE TITLE
visualization codes bug

### ISSUE THREAD

**Issue by tfzhou** [ifzhang/FairMOT#28]
https://github.com/ifzhang/FairMOT/blob/6a84666ac2b6f66557758e8e0fa802c47ef0aca9/src/lib/datasets/dataset/jde.py#L209

Thanks for the great project! It seems that the above line does not fit current codes. It will plot well with: 
```
plt.plot(labels[:, [2, 4, 4, 2, 2]].T, labels[:, [3, 3, 5, 5, 3]].T, '.-')
```

**Comment by ifzhang** [comment]
Thanks! I did not notice that before.
