### ISSUE TITLE
Is Kalman filtering also used in model training?

### ISSUE THREAD

**Issue by ShellyLingling** [ifzhang/FairMOT#281]
https://github.com/ifzhang/FairMOT/issues/109#issuecomment-630120170  “We just use kalman filter in testing. ”

@ifzhang   我看到您在这个问题里的回答，是指卡尔曼滤波只在test的时候使用，但是我看multitracker.py中JDETracker里面是使用了卡尔曼滤波的。所以我有点困惑，希望能得到老师的回答。

**Comment by developer0hye** [comment]
I think that kalman filter doesn't affect model to be trained.

**Comment by ShellyLingling** [comment]
> I think that kalman filter doesn't affect model to be trained.

My custom dataset contains strenuous movements (such as somersaults). Appearance characteristics change quickly between frames.
According to https://github.com/ifzhang/FairMOT/issues/266#issue-726009447. 
I wonder if I need to remove the Kalman filter.
Could you give me some advice?

**Comment by developer0hye** [comment]
@ShellyLingling 

I understood that Kalman filter is especially used to estimate motion when object is fully occluded.

If we adopt the kalman filter to our custom dataset, the position of object would be changed from original annotated position. I think it would give model ambiguity. But to adopt kalman filter during inference stage would make better tracking results.

**Comment by ShellyLingling** [comment]
> If we adopt the kalman filter to our custom dataset, the position of object would be changed from originally annotated position.
sorry, I don't understand this sentence
@developer0hye  Thank you!!!  I still have a question. Can the Kalman filter be used on targets with sudden changes in trajectory?

**Comment by developer0hye** [comment]
@ShellyLingling It's hard to think of the results!... If you have good result, tell me about, plz

**Comment by ShellyLingling** [comment]
there is no Kalman filtering in model training.I'm sorry for asking this stupid question.
