### ISSUE TITLE
After running the demo.py, the result.txt is empty. Why?

### ISSUE THREAD

**Issue by niraj-bhujel** [ifzhang/FairMOT#283]
After sucessfully running the demo.py, it results nothing
`cd src
python demo.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.4`

2020-11-17 22:45:46 [INFO]: Starting tracking...
2020-11-17 22:45:46 [INFO]: Starting tracking...
2020-11-17 22:45:46 [INFO]: Starting tracking...
2020-11-17 22:45:46 [INFO]: Starting tracking...
2020-11-17 22:45:46 [INFO]: Starting tracking...
2020-11-17 22:45:46 [INFO]: Starting tracking...
2020-11-17 22:45:46 [INFO]: Starting tracking...
2020-11-17 22:45:46 [INFO]: Starting tracking...
Reloaded modules: _init_paths, tracker.multitracker, models.decode, models.utils, models.model, models.networks.dlav0, models.networks.pose_dla_dcn, models.networks.DCNv2.dcn_v2, _ext, models.networks.pose_hrnet, models.networks.config, models.networks.config.default, models.networks.resnet_dcn, models.networks.resnet_fpn_dcn, tracking_utils.kalman_filter, tracking_utils.log, tracking_utils.utils, utils.post_process, utils.image, tracker.basetrack, tracking_utils.timer, tracking_utils.evaluation, tracking_utils.io, datasets.dataset.jde, opts, utils.utils
Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /home/dl-asoro/Desktop/multi-target-tracking@dlasoro/FairMOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 2, 'id': 512, 'reg': 2}
Lenth of the video: 1500 frames
Creating model...
loaded ../models/fairmot_dla34.pth, epoch 30
Skip loading parameter wh.2.weight, required shapetorch.Size([2, 256, 1, 1]), loaded shapetorch.Size([4, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter wh.2.bias, required shapetorch.Size([2]), loaded shapetorch.Size([4]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter id.2.weight, required shapetorch.Size([512, 256, 1, 1]), loaded shapetorch.Size([128, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter id.2.bias, required shapetorch.Size([512]), loaded shapetorch.Size([128]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
2020-11-17 22:45:46 [INFO]: Processing frame 0 (100000.00 fps)
2020-11-17 22:45:46 [INFO]: Processing frame 0 (100000.00 fps)
2020-11-17 22:45:46 [INFO]: Processing frame 0 (100000.00 fps)
2020-11-17 22:45:46 [INFO]: Processing frame 0 (100000.00 fps)
2020-11-17 22:45:46 [INFO]: Processing frame 0 (100000.00 fps)
2020-11-17 22:45:46 [INFO]: Processing frame 0 (100000.00 fps)
2020-11-17 22:45:46 [INFO]: Processing frame 0 (100000.00 fps)
2020-11-17 22:45:46 [INFO]: Processing frame 0 (100000.00 fps)
2020-11-17 22:45:49 [INFO]: Processing frame 20 (10.14 fps)
2020-11-17 22:45:49 [INFO]: Processing frame 20 (10.14 fps)
2020-11-17 22:45:49 [INFO]: Processing frame 20 (10.14 fps)
2020-11-17 22:45:49 [INFO]: Processing frame 20 (10.14 fps)
2020-11-17 22:45:49 [INFO]: Processing frame 20 (10.14 fps)
2020-11-17 22:45:49 [INFO]: Processing frame 20 (10.14 fps)
2020-11-17 22:45:49 [INFO]: Processing frame 20 (10.14 fps)
2020-11-17 22:45:49 [INFO]: Processing frame 20 (10.14 fps)
.
.
.
2020-11-17 22:49:09 [INFO]: Processing frame 1480 (9.98 fps)
2020-11-17 22:49:09 [INFO]: Processing frame 1480 (9.98 fps)
2020-11-17 22:49:09 [INFO]: Processing frame 1480 (9.98 fps)
2020-11-17 22:49:09 [INFO]: Processing frame 1480 (9.98 fps)
2020-11-17 22:49:09 [INFO]: Processing frame 1480 (9.98 fps)
2020-11-17 22:49:12 [INFO]: save results to ../results/results.txt
2020-11-17 22:49:12 [INFO]: save results to ../results/results.txt
2020-11-17 22:49:12 [INFO]: save results to ../results/results.txt
2020-11-17 22:49:12 [INFO]: save results to ../results/results.txt
2020-11-17 22:49:12 [INFO]: save results to ../results/results.txt
2020-11-17 22:49:12 [INFO]: save results to ../results/results.txt
2020-11-17 22:49:12 [INFO]: save results to ../results/results.txt
2020-11-17 22:49:12 [INFO]: save results to ../results/results.txt
ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[mjpeg @ 0x1aae1c0] Changeing bps to 8
Input #0, image2, from '../results/frame/%05d.jpg':
  Duration: 00:01:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn, 25 tbc
Please use -b:a or -b:v, -b is ambiguous
[swscaler @ 0x1ac94e0] deprecated pixel format used, make sure you did set range correctly
Output #0, mp4, to '../results/result.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: mpeg4 ( [0][0][0] / 0x0020), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 5000 kb/s, 25 fps, 12800 tbn, 25 tbc
    Metadata:
      encoder         : Lavc56.60.100 mpeg4
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mpeg4 (native))
Press [q] to stop, [?] for help
frame= 1500 fps= 76 q=3.8 Lsize=   36719kB time=00:01:00.00 bitrate=5013.4kbits/s    rame=   76 fps= 75 q=4.4 size=    2037kB time=00:00:03.04 bitrate=5489.4kbits/s    frame=  115 fps= 75 q=4.6 size=    2967kB time=00:00:04.60 bitrate=5283.1kbits/s    frame=  154 fps= 76 q=4.3 size=    3898kB time=00:00:06.16 bitrate=5184.3kbits/s    frame=  193 fps= 76 q=3.3 size=    4913kB time=00:00:07.72 bitrate=5213.6kbits/s    frame=  232 fps= 76 q=4.4 size=    5828kB time=00:00:09.28 bitrate=5144.5kbits/s    frame=  272 fps= 77 q=4.8 size=    6788kB time=00:00:10.88 bitrate=5111.1kbits/s    frame=  312 fps= 77 q=4.2 size=    7737kB time=00:00:12.48 bitrate=5078.9kbits/s    frame=  351 fps= 77 q=4.9 size=    8753kB time=00:00:14.04 bitrate=5107.3kbits/s    frame=  390 fps= 77 q=4.8 size=    9678kB time=00:00:15.60 bitrate=5082.4kbits/s    frame=  429 fps= 77 q=4.4 size=   10610kB time=00:00:17.16 bitrate=5065.2kbits/s    frame=  468 fps= 77 q=4.4 size=   11546kB time=00:00:18.72 bitrate=5052.7kbits/s    frame=  507 fps= 77 q=5.5 size=   12593kB time=00:00:20.28 bitrate=5086.9kbits/s    frame=  545 fps= 77 q=5.3 size=   13490kB time=00:00:21.80 bitrate=5069.1kbits/s    frame=  583 fps= 77 q=5.1 size=   14388kB time=00:00:23.32 bitrate=5054.4kbits/s    frame=  621 fps= 77 q=5.4 size=   15310kB time=00:00:24.84 bitrate=5049.2kbits/s    frame=  660 fps= 77 q=5.1 size=   16238kB time=00:00:26.40 bitrate=5038.6kbits/s    frame=  697 fps= 76 q=3.8 size=   17224kB time=00:00:27.88 bitrate=5060.9kbits/s    frame=  735 fps= 76 q=5.0 size=   18127kB time=00:00:29.40 bitrate=5050.9kbits/s    frame=  773 fps= 76 q=5.3 size=   19052kB time=00:00:30.92 bitrate=5047.7kbits/s    frame=  812 fps= 76 q=5.1 size=   19968kB time=00:00:32.48 bitrate=5036.2kbits/s    frame=  851 fps= 76 q=5.1 size=   20918kB time=00:00:34.04 bitrate=5034.1kbits/s    frame=  889 fps= 76 q=3.9 size=   21911kB time=00:00:35.56 bitrate=5047.6kbits/s    frame=  927 fps= 76 q=4.9 size=   22803kB time=00:00:37.08 bitrate=5037.9kbits/s    frame=  966 fps= 76 q=5.2 size=   23750kB time=00:00:38.64 bitrate=5035.2kbits/s    frame= 1004 fps= 76 q=5.2 size=   24658kB time=00:00:40.16 bitrate=5029.8kbits/s    frame= 1042 fps= 76 q=4.4 size=   25564kB time=00:00:41.68 bitrate=5024.6kbits/s    frame= 1080 fps= 76 q=4.6 size=   26483kB time=00:00:43.20 bitrate=5021.9kbits/s    frame= 1118 fps= 76 q=5.3 size=   27500kB time=00:00:44.72 bitrate=5037.5kbits/s    frame= 1156 fps= 76 q=5.4 size=   28412kB time=00:00:46.24 bitrate=5033.5kbits/s    frame= 1194 fps= 76 q=5.4 size=   29319kB time=00:00:47.76 bitrate=5028.9kbits/s    frame= 1232 fps= 76 q=4.7 size=   30215kB time=00:00:49.28 bitrate=5022.8kbits/s    frame= 1270 fps= 76 q=4.4 size=   31130kB time=00:00:50.80 bitrate=5020.1kbits/s    frame= 1308 fps= 76 q=4.7 size=   32042kB time=00:00:52.32 bitrate=5016.9kbits/s    frame= 1346 fps= 76 q=4.6 size=   33028kB time=00:00:53.84 bitrate=5025.3kbits/s    frame= 1385 fps= 76 q=5.2 size=   33985kB time=00:00:55.40 bitrate=5025.3kbits/s    frame= 1423 fps= 76 q=4.8 size=   34888kB time=00:00:56.92 bitrate=5021.1kbits/s    frame= 1461 fps= 76 q=4.8 size=   35803kB time=00:00:58.44 bitrate=5018.8kbits/s    frame= 1500 fps= 76 q=3.8 size=   36711kB time=00:01:00.00 bitrate=5012.3kbits/s    
video:36711kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.021103%

After this, I checked the result.txt file, but it is empty. The result.mp4 doesn't contain any information except frame:0 fps:10.8 num:0 on the top left. Is it possible to get the video result as in MOT challenge results? Thanks in advance.

**Comment by niraj-bhujel** [comment]
I loaded the wrong version of the model. Please not the following error. 

> Skip loading parameter wh.2.weight, required shapetorch.Size([2, 256, 1, 1]), loaded shapetorch.Size([4, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.

**Comment by ZhangYuef** [comment]
> I loaded the wrong version of the model. Please note the following error.
> 
> > Skip loading parameter wh.2.weight, required shapetorch.Size([2, 256, 1, 1]), loaded shapetorch.Size([4, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.

Face same problem. What do you mean 'the wrong version of the model' here?

**Comment by usmcseal911** [comment]
> > I loaded the wrong version of the model. Please note the following error.
> > > Skip loading parameter wh.2.weight, required shapetorch.Size([2, 256, 1, 1]), loaded shapetorch.Size([4, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
> 
> Face same problem. What do you mean 'the wrong version of the model' here?

use ur newest trained model
