### ISSUE TITLE
'collate_fn' is not in dataset.jde

### ISSUE THREAD

**Issue by huiyan-dev** [ifzhang/FairMOT#293]
I am sorry to disturb you and you can see my issue as follow:
-------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:/FairMOT/src/test_det.py", line 18, in <module>
    from datasets.dataset.jde import DetDataset, collate_fn
ImportError: cannot import name 'collate_fn' from 'datasets.dataset.jde' (E:\FairMOT\src\lib\datasets\dataset\jde.py)
-------------------------------------------------------------------------------------------------------------------------------------
Can you tell me that what is the function of 'collate_fn'?
Should I ignore this problem?
I am a fresh man and the first time debug a project about MOT.
Thank for your answer.

**Comment by ifzhang** [comment]
I add it in jde.py. Thank you for your comment.
