### ISSUE TITLE
zero detection, even with mot_16 video.

### ISSUE THREAD

**Issue by yesh2007** [ifzhang/FairMOT#298]
![00187](https://user-images.githubusercontent.com/43289345/101180315-6e05a480-3671-11eb-8f9c-4b54c5fff58f.jpg)

Followed steps for demo, as given on the web(https://github.com/ifzhang/FairMOT).
Tried it on Linux system with GPU. No proper detection and tracking.

**Comment by YagnikThanki** [comment]
@yesh2007 You need to use **fairmot_dla34.pth**. You will find the link of this model in README.
