### ISSUE TITLE
AttributeError: 'LoadImages' object has no attribute 'files'

### ISSUE THREAD

**Issue by yuehui130** [ifzhang/FairMOT#299]
I want to try the default settings to run track.py.  
`python track.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.6`
（I have executed the “python gen_labels_15.py” command on MOT15 data）
Then I got such an error.

`Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  D:\work\FairMOT-master\FairMOT-master\src\lib\..\..\exp\mot\default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
2020-12-05 21:16:04 [INFO]: start seq: ADL-Rundle-1
Traceback (most recent call last):
  File "track.py", line 278, in <module>
    save_videos=False)
  File "track.py", line 131, in main
    dataloader = datasets.LoadImages(osp.join(data_root, seq, 'img1'), opt.img_size)
  File "D:\work\FairMOT-master\FairMOT-master\src\lib\datasets\dataset\jde.py", line 32, in __init__
    self.nF = len(self.files)  # number of image files
AttributeError: 'LoadImages' object has no attribute 'files'`

Can someone tell me why this happens and how to solve it?
And, how, where to load the data set.

**Comment by ifzhang** [comment]
You can check the path of "osp.join(data_root, seq, 'img1')" and see whether it have images.

**Comment by yuehui130** [comment]
Great, the owner responded quickly.  I checked the path and found the problem.
I run on windows. So I changed the "data_dir" in opts.py. It worked.  Thank you very much.
On line 127.
`self.parser.add_argument('--data_dir', type=str, default='D:/work/FairMOT-master/FairMOT-master/src/data')`
