### ISSUE TITLE
How to get the offline results?

### ISSUE THREAD

**Issue by changwh** [ifzhang/FairMOT#30]
Hello, thanks for your great work! 
It is mentioned in the paper that your tracker also achieves the highest MOTA score among all online and offline trackers. And in this repo, the code seems could get only online results. Am I right?
And to get the offline results, how do I modify the code?

**Comment by ifzhang** [comment]
We can only get the online results.  We use our online results to compare with other offline trackers.

**Comment by changwh** [comment]
> 
> 
> We can only get the online results. We use our online results to compare with other offline trackers.

Ok, thanks for your reply. lol
