### ISSUE TITLE
Questions about scales change

### ISSUE THREAD

**Issue by oomq** [ifzhang/FairMOT#302]
Hi @ifzhang 
Thanks for sharing the great work that you have done!
However, I found a probelm when I trained my custom dataset about fish. When the fish changes from vertical to horizontal, the id will be changed.
Would you please tell me where can I modify the code or some adivises?

**Comment by ifzhang** [comment]
It seems that the reid feature of the fish is hard to learn. You can try only using bbox IOU or the distance of the center of the fish during tracking.
