### ISSUE TITLE
The hrnetv2_w18_imagenet_pretrained.pth

### ISSUE THREAD

**Issue by zwy1996** [ifzhang/FairMOT#32]
Hello, nice work!

When I used your code. I should download the hrnetv2_w18_imagenet_pretrained.pth. But  I found this was very slowly. Could help me with a baiduyunpan about the hrnetv2_w18_imagenet_pretrained.pth. Thank you very much!

**Comment by zubairahmed-ai** [comment]
Yes its slow

**Comment by ifzhang** [comment]
Baidu link is here:
https://pan.baidu.com/share/init?surl=Px_g1E2BLVRkKC5t-b-R5Q
code: r5xn
It's from the official repo of HRNet:
https://github.com/HRNet/HRNet-Image-Classification

**Comment by zwy1996** [comment]
@ifzhang ，Thank you very much!
