### ISSUE TITLE
ffmpeg Error

### ISSUE THREAD

**Issue by caglarmert** [ifzhang/FairMOT#33]
When I try to run the demo.py using the following command:
`python demo.py mot --load_model ../models/all_dla34.pth --conf_thres 0.4`
I get the following error, when I traced it I found out it is an error related to ffmpeg. Anyone experienced or fixed this error?

[image2 @ 0000024a478eba00] Could find no file with path '../results\frame/%05d.jpg' and index in the range 0-4
../results\frame/%05d.jpg: No such file or directory

I have installed miniconda, cython-bbox, CUDA and other requirements as suggested by the readme and fixed their relative errors I encountered.

Also thank you for your work 👍

**Comment by zubairahmed-ai** [comment]
See this issue https://github.com/ifzhang/FairMOT/issues/5

**Comment by FLyingLSJ** [comment]
You can set para **save_videos=False** in `FairMOT/src/track.py`

![](https://user-images.githubusercontent.com/18750080/79442047-99685000-800a-11ea-82c3-da3adf40c587.png)

or install ffmpeg (My system is Ubuntu 16.04)

`
apt update
apt install ffmpeg
# input  y
ffmpeg -version
`

![image](https://user-images.githubusercontent.com/18750080/79442588-5490e900-800b-11ea-9b88-91d49df1de57.png)

**Comment by caglarmert** [comment]
@FLyingLSJ Thank you, I have windows ffmpeg build, I will try your version because the error I get is common for other libraries and repositories so it must be ffmpeg build error on my side. Also the parameters save_videos=False was already set to False for me.

![image](https://user-images.githubusercontent.com/32517442/79449855-a0806580-7fec-11ea-8610-c8aa5b07dec8.png)


@zubairahmed-ai Thank you kind sir, I see you have went through errors I have also encountered I will follow your comments in the issue and your methods as well. Thank you again.
