### ISSUE TITLE
Tracked object

### ISSUE THREAD

**Issue by NaifahNurya** [ifzhang/FairMOT#335]
This is not an issue but needs help.  I would like to ask @ifzhang  or any other one who has an idea about How to crop and save the resulting tracked object as separate image files in another folder. In which file should I focus on this??  Because I tried to modify  on visualization.py located in https://github.com/ifzhang/FairMOT/blob/master/src/lib/tracking_utils/visualization.py by  putting the following 
        
```
        trackobject_crop = image[int(y1):int(y1+h), int(x1):int(x1+w)]
        trackobject_crop = cv2.resize(trackobject_crop, (512,512), interpolation=cv2.INTER_CUBIC)
		
    return  trackobject_crop
```
 in line 54 and 55 and then returning trackobject_crop instead of `returning im`  but only a single person cropped and returned for the first 20 frames only with the following error.

```
Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    demo(opt)
  File "demo.py", line 30, in demo
    eval_seq(opt, dataloader, 'mot', result_filename, save_dir=frame_dir, show_image=False, frame_rate=frame_rate)
  File "C:\Users\Desktop\FairMOT\src\track.py", line 79, in eval_seq
    online_im = vis.plot_tracking(img0, online_tlwhs, online_ids, frame_id=frame_id)
  File "C:\Users\Desktop\FairMOT\src\lib\tracking_utils\visualization.py", line 74, in plot_tracking
    trackobject_crop = cv2.resize(trackobject_crop ,(512,512), interpolation=cv2.INTER_CUBIC)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6sxsq0tp\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

Any help for solving this??

**Comment by Smirkey** [comment]
Hi !

In multitracker.py there's a piece of code dedicated to viz, you can change it a little to save tracked objects :)

**https://github.com/ifzhang/FairMOT/blob/ca63d27f19e8d2170b84edb80cc2dc348c3dcd5a/src/lib/tracker/multitracker.py#L268-L275**

Best,
Smirkey

**Comment by NaifahNurya** [comment]
Hi @Smirkey, Thank you for the advice 
However; I tried to understand it but still got some challenges. Can you try and share the modified version. When I read the code I thought maybe file visualization.py and track.py might be relevant for this task.

**Comment by NaifahNurya** [comment]
Any help @ifzhang and others

**Comment by Hemilibeatriz** [comment]
Hi @NaifahNurya, some news about this?
