### ISSUE TITLE
'id_loss' doesnt reduce at all

### ISSUE THREAD

**Issue by RamkumarSakthivel** [ifzhang/FairMOT#347]
I am training hrnet-32 model from scratch on the BDD100k MOT dataset, but the id_loss doesn't reduce at all. It stays around 11 even after 10 epochs. Does anyone have any idea why?

**Comment by May2333** [comment]
Hi, I'm facing the same problem with u: the id loss stay around 5.3-5.8 even after 30 epoch. Do you figure it out?
Any reply will be help!

**Comment by RamkumarSakthivel** [comment]
Apparently, ReID is a classification task in this work. So it is difficult to reduce id_loss, especially with so many different IDs in a driving scene, which is the case in the BDD100k MOT dataset. Thanks to @dingwoai for this answer. Hope this helps!
