### ISSUE TITLE
Loss jumps after loading checkpoint

### ISSUE THREAD

**Issue by NosremeC** [ifzhang/FairMOT#364]
I am not sure if I am the only person encountered this issue. So after I loaded the checkpoint and resumed the training, the loss which was <1 jumped back almost to the original level (>10) as when I first started the training. The problem resided in the ID loss, it always went up after resuming. Does anyone have any idea or have had any similar issues? Many thanks!

**Comment by yunseung-dable** [comment]
I have same problem. does anyone knows why it happens?

**Comment by NosremeC** [comment]
> I have same problem. does anyone knows why it happens?

Yes. It is because the classifier used for reid and the parameters used in uncertainty loss are never saved in the checkpoint. These parts are reset everytime as you load the checkpoint and resume the training. You can refer to #214. 

To solve this problem simply modify save_model() in model.py to save these parameter and load_model() to load them. After that you should be in the good shape.

**Comment by LX0912R** [comment]
Have you solved this problem? And can you share the solution of save_model()？ Thanks @hvt1609

**Comment by LX0912R** [comment]
Have you solved this issue? And can you share the solution of save_model()？ Thanks @hvt1609
