### ISSUE TITLE
make error！

### ISSUE THREAD

**Issue by quuhua911** [ifzhang/FairMOT#37]
cuda10.2 or cuda9.0，Ubuntu18.04 

Follow your installation instructions, but make error。What can I do to fix this

sh make.sh
running build
running build_ext
building '_ext' extension
/home/quh/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/quh/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/quh/anaconda3/include -fPIC -DWITH_CUDA -I/home/quh/pythonwork/FairMOT/src/lib/models/networks/DCNv2/src -I/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include -I/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include/TH -I/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.2:/usr/local/cuda/include -I/home/quh/anaconda3/include/python3.7m -c /home/quh/pythonwork/FairMOT/src/lib/models/networks/DCNv2/src/vision.cpp -o build/temp.linux-x86_64-3.7/home/quh/pythonwork/FairMOT/src/lib/models/networks/DCNv2/src/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
/home/quh/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/quh/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/quh/anaconda3/include -fPIC -DWITH_CUDA -I/home/quh/pythonwork/FairMOT/src/lib/models/networks/DCNv2/src -I/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include -I/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include/TH -I/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.2:/usr/local/cuda/include -I/home/quh/anaconda3/include/python3.7m -c /home/quh/pythonwork/FairMOT/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_cpu.cpp -o build/temp.linux-x86_64-3.7/home/quh/pythonwork/FairMOT/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /home/quh/pythonwork/FairMOT/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_cpu.cpp:4:0:
/home/quh/anaconda3/envs/people-detection/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/home/quh/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1

**Comment by ifzhang** [comment]
It seems the version of gcc is not matched. You may refer to issue #12. If there's still something wrong when building DCNv2, you can skip the making process and use HRNet which do not use DCNv2 instead. HRNet also achieves good results.

**Comment by quuhua911** [comment]
I had changed  gcc and g++  to  7.5  , But it still couldn't fix the problem

**Comment by ifzhang** [comment]
Pytorch should be > 1.0

**Comment by quuhua911** [comment]
All the packages you mentioned have been installed
(FairMOT) quh@quh-Z370P-D3:~/pythonwork/FairMOT$ conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
Solving environment: done
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.8.3
Please update conda by running
    $ conda update -n base -c defaults conda
# All requested packages already installed.

**Comment by quuhua911** [comment]
The problem has been solved and can be closed.

**Comment by CaptainEven** [comment]
> All the packages you mentioned have been installed
> (FairMOT) quh@quh-Z370P-D3:~/pythonwork/FairMOT$ conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
> Solving environment: done
> ==> WARNING: A newer version of conda exists. <==
> current version: 4.5.11
> latest version: 4.8.3
> Please update conda by running
> $ conda update -n base -c defaults conda
> All requested packages already installed.

Hi, how u solved the compiling problem?

**Comment by LV0913** [comment]
Hey, I have meet the same problem as yours. Can you tell me your solution?

**Comment by yustaub** [comment]
@quuhua911  can u share how to solve this?

**Comment by ZiyanZhu1994** [comment]
same issue here, anyone has fixed it? Thanks
