### ISSUE TITLE
Box size ratio

### ISSUE THREAD

**Issue by Bennnun** [ifzhang/FairMOT#387]
Hi,
First thanks for the great repo.
I managed to train many models for specific objects other than pedestrians, but i am having a trouble with one type of object that has a different height to width ratio.
The object is usually detected but when the box width grows, the detection is lost.
I would like to ask where in the code are the potential boxes' sizes are defined in order to try changing them to particular ratios.
Thanks.

**Comment by Choneke** [comment]
@Bennnun you can refer to [https://github.com/ifzhang/FairMOT/blob/ca63d27f19e8d2170b84edb80cc2dc348c3dcd5a/src/track.py]  line number 97 and 98

```
vertical = tlwh[2] / tlwh[3] &gt; 1.6            
if tlwh[2] * tlwh[3] &gt; opt.min_box_area and not vertical:
```

**Comment by Bennnun** [comment]
@Choneke thanks a lot. Starting a new training right away.

**Comment by wyy19990** [comment]
Could you please tell me how to adjust the size of the object detection box? I need to adjust the object detection box to be wider than the height @Choneke
