### ISSUE TITLE
 not fully load the pre-trained weights, Is this normal?, when I run the shell command "python train.py  ***", 

### ISSUE THREAD

**Issue by hp-93** [ifzhang/FairMOT#39]
![image](https://user-images.githubusercontent.com/35527573/79460817-f1fa1600-8027-11ea-8c7b-4f8fb899ce9c.png)

**Comment by ifzhang** [comment]
Because the pretrained model is trained on COCO and is different from our model, so we just load the backbone parameters of the pretrained model. It is normal.

**Comment by hp-93** [comment]
ok, thanks
