### ISSUE TITLE
Loss changes to negative number when training

### ISSUE THREAD

**Issue by Maping1026** [ifzhang/FairMOT#390]
@ifzhang Thank you for your amazing work! Sorry to bother you.
when I train the MOT17, loss seems nomal （Continued to drop），but it changes to negative number after few epochs, 
as shown in the afigure below：
![2](https://user-images.githubusercontent.com/70265376/121513494-7aeac280-ca1d-11eb-819b-4cf8ce847bd3.PNG)

and it still continued to drop:
Continued to decline, like this
mot/default| train: [10][929/2658]|Tot: 0:15:44 |ETA: 0:00:00 |loss -0.5303 |hm_loss 0.0052 |wh_loss 0.6878 |off_loss 0.1891 |id_loss 0.1677 |Data 0.027s(0.032s) |Net 1.015s
mot/default| train: [10][930/2658]|Tot: 0:15:45 |ETA: 0:00:00 |loss -0.5307 |hm_loss 0.0052 |wh_loss 0.6876 |off_loss 0.1891 |id_loss 0.1675 |Data 0.029s(0.032s) |Net 1.015s
mot/default| train: [10][931/2658]|Tot: 0:15:46 |ETA: 0:00:00 |loss -0.5310 |hm_loss 0.0052 |wh_loss 0.6873 |off_loss 0.1891 |id_loss 0.1674 |Data 0.028s(0.032s) |Net 1.015s
mot/default| train: [10][932/2658]|Tot: 0:15:47 |ETA: 0:00:00 |loss -0.5311 |hm_loss 0.0052 |wh_loss 0.6872 |off_loss 0.1891 |id_loss 0.1674 |Data 0.033s(0.032s) |Net 1.015s
mot/default| train: [10][933/2658]|Tot: 0:15:48 |ETA: 0:00:00 |loss -0.5300 |hm_loss 0.0052 |wh_loss 0.6888 |off_loss 0.1891 |id_loss 0.1677 |Data 0.021s(0.032s) |Net 1.015s
mot/default| train: [10][934/2658]|Tot: 0:15:49 |ETA: 0:00:00 |loss -0.5302 |hm_loss 0.0052 |wh_loss 0.6885 |off_loss 0.1892 |id_loss 0.1676 |Data 0.026s(0.032s) |Net 1.015s
mot/default| train: [10][935/2658]|Tot: 0:15:50 |ETA: 0:00:00 |loss -0.5307 |hm_loss 0.0052 |wh_loss 0.6880 |off_loss 0.1891 |id_loss 0.1675 |Data 0.028s(0.032s) |Net 1.015s
mot/default| train: [10][936/2658]|Tot: 0:15:51 |ETA: 0:00:00 |loss -0.5310 |hm_loss 0.0052 |wh_loss 0.6878 |off_loss 0.1891 |id_loss 0.1674 |Data 0.029s(0.032s) |Net 1.015s
mot/default| train: [10][937/2658]|Tot: 0:15:52 |ETA: 0:00:00 |loss -0.5314 |hm_loss 0.0052 |wh_loss 0.6875 |off_loss 0.1891 |id_loss 0.1672 |Data 0.027s(0.032s) |Net 1.015s
mot/default| train: [10][938/2658]|Tot: 0:15:53 |ETA: 0:00:00 |loss -0.5311 |hm_loss 0.0052 |wh_loss 0.6873 |off_loss 0.1891 |id_loss 0.1674 |Data 0.027s(0.032s) |Net 1.015s
mot/default| train: [10][939/2658]|Tot: 0:15:54 |ETA: 0:00:00 |loss -0.5308 |hm_loss 0.0052 |wh_loss 0.6880 |off_loss 0.1892 |id_loss 0.1674 |Data 0.028s(0.032s) |Net 1.015s
mot/default| train: [10][940/2658]|Tot: 0:15:55 |ETA: 0:00:00 |loss -0.5308 |hm_loss 0.0052 |wh_loss 0.6883 |off_loss 0.1892 |id_loss 0.1674 |Data 0.025s(0.032s) |Net 1.015s
mot/default| train: [10][941/2658]|Tot: 0:15:56 |ETA: 0:00:00 |loss -0.5311 |hm_loss 0.0052 |wh_loss 0.6880 |off_loss 0.1892 |id_loss 0.1672 |Data 0.029s(0.032s) |Net 1.015s
mot/default| train: [10][942/2658]|Tot: 0:15:57 |ETA: 0:00:00 |loss -0.5308 |hm_loss 0.0052 |wh_loss 0.6883 |off_loss 0.1892 |id_loss 0.1673 |Data 0.028s(0.032s) |Net 1.016s
mot/default| train: [10][943/2658]|Tot: 0:15:58 |ETA: 0:00:00 |loss -0.5310 |hm_loss 0.0052 |wh_loss 0.6881 |off_loss 0.1892 |id_loss 0.1672 |Data 0.028s(0.032s) |Net 1.016s
mot/default| train: [10][944/2658]|Tot: 0:15:59 |ETA: 0:00:00 |loss -0.5314 |hm_loss 0.0052 |wh_loss 0.6877 |off_loss 0.1892 |id_loss 0.1671 |Data 0.031s(0.032s) |Net 1.016s
mot/default| train: [10][945/2658]|Tot: 0:16:00 |ETA: 0:00:00 |loss -0.5315 |hm_loss 0.0052 |wh_loss 0.6872 |off_loss 0.1892 |id_loss 0.1671 |Data 0.027s(0.032s) |Net 1.016s
mot/default| train: [10][946/2658]|Tot: 0:16:01 |ETA: 0:00:00 |loss -0.5316 |hm_loss 0.0052 |wh_loss 0.6871 |off_loss 0.1892 |id_loss 0.1671 |Data 0.029s(0.032s) |Net 1.016s
mot/default| train: [10][947/2658]|Tot: 0:16:02 |ETA: 0:00:00 |loss -0.5315 |hm_loss 0.0052 |wh_loss 0.6869 |off_loss 0.1892 |id_loss 0.1672 |Data 0.026s(0.032s) |Net 1.016s
mot/default| train: [10][948/2658]|Tot: 0:16:03 |ETA: 0:00:00 |loss -0.5318 |hm_loss 0.0052 |wh_loss 0.6870 |off_loss 0.1891 |id_loss 0.1670 |Data 0.027s(0.032s) |Net 1.016s
mot/default| train: [10][949/2658]|Tot: 0:16:04 |ETA: 0:00:00 |loss -0.5321 |hm_loss 0.0052 |wh_loss 0.6872 |off_loss 0.1891 |id_loss 0.1669 |Data 0.027s(0.032s) |Net 1.016s

I've been troubled for a long time， very very very need help!!!!!

**Comment by sam99dave** [comment]
Did u solve this? If yes then what was the reason behind this behavior?

**Comment by AI-Hunter** [comment]
@Maping1026 
same problem, would you tell me, how have you solved it?
Thanks
