### ISSUE TITLE
Load pretrained model

### ISSUE THREAD

**Issue by LeDuySon** [ifzhang/FairMOT#401]
How can i load the pretrained backbone model like ctdet_coco_dla_2x.pth? i have found a line that load backbone model but it has been commented out.
![Screenshot from 2021-06-24 09-34-17](https://user-images.githubusercontent.com/33374938/123193673-66073800-d4cf-11eb-8435-ec17fd979696.png)

**Comment by zengjie617789** [comment]
i think it should be this line to change the backbone:
```
self.parser.add_argument('--arch', default='dla_34', 
                             help='model architecture. Currently tested'
                                  'resdcn_34 | resdcn_50 | resfpndcn_34 |'
                                  'dla_34 | hrnet_18')
```
