### ISSUE TITLE
Custom detector & Pedestrian dataset

### ISSUE THREAD

**Issue by anhnktp** [ifzhang/FairMOT#42]
Nice works !
I trained succesfully with almost datasets. Now I have intention to train from multiple datasets to create baseline model, but I have some issues when downloaded Caltech Pedestrian & City Person dataset
I followed instruction at: https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/DATASET_ZOO.md.
With Caltech Pedestrian dataset, I downloaded all *.tar file from but I don't know how to convert *.seq file to sequence of .png file (or .jpg)
With City Person dataset, I downloaded from Gdrive link but it seems Citypersons.z03 file is not final part zip

Could you pls share link download Cityperson & Caltech_pedestrian dataset (have images & label_with_ids)

One more question, do your code support change custom detector instead of CenterNet detector ?

Thank you so much !

**Comment by ifzhang** [comment]
You may use https://github.com/DanLiu0623/caltect_dataset_convert/blob/master/convert_seq_to_jpg.py as a reference to convert seq to jpg. 
As for the detector, I think it is difficult to change to other detectors because we have a reid head in CenterNet which jointly performs detection and tracking.

**Comment by anhnktp** [comment]
Tks !! I converted successfully Caltech dataset. 
For custom detector, I think your choice DLA34 is the best because it is anchor free based and real time speed. 
Have you tried some ideas in this paper: https://arxiv.org/pdf/1809.04427.pdf. I think it can improve more in case of occlusion (select candidates bbox from both detection & tracks, if bad detection because of occlusion, choose high score tracks instead). It can minimize ID switch more

**Comment by amitbcp** [comment]
@anhnktp can you please help me how did you create label_with_ids for Caltech ?
