### ISSUE TITLE
about eval mot datasets

### ISSUE THREAD

**Issue by YmanChris** [ifzhang/FairMOT#421]
I use official model "fairmot_dla34.pth", and run the command "python src/track.py --val_mot17 True --data_dir /home/w330/workspace/yxy/dataset mot --load_model ./models/fairmot_dla34.pth --conf_thres 0.3"
But the effect is too bad. I try to use mot15、 mot16、 mot17. The results all like this.
![image](https://user-images.githubusercontent.com/18142592/127731588-d53258f0-2a02-407c-be1b-aac096b53e35.png)

**Comment by Gaoxinyue423** [comment]
I have the same problem. How did you solve it?
