### ISSUE TITLE
Custom dataset training issue

### ISSUE THREAD

**Issue by AMYEY** [ifzhang/FairMOT#422]
Hi I want to train custom dataset and I followed all the steps mentioned in readme. 
When I execute `experiments/mix_dla34.sh --data_cfg '../src/lib/cfg/custom.json'` I get the error 
`OSError: /home/zyf/dataset/MOT17/labels_with_ids/train/MOT17-02-SDP/img1/000001.txt not found.`. 

I have specified the "root" and "train" keys in the json file and changed the 'data_dir' in src/lib/opts.py along with --data_cfg. What am I missing? 

![image](https://user-images.githubusercontent.com/86493381/128011785-c91cf063-6bb5-47b5-a782-5747baf79a0e.png)

Thank you!

**Comment by danishmansari** [comment]
@AMYEY I am getting same error, were you able to resolve this?

**Comment by danishmansari** [comment]
There are below steps you need to follow:
1. Change "root" and "data_dir" as described in readme file.
2. generate labels using src/generate_lables_with_ids script, (for this to run you need to move train/val/test in MOT17) to images directory.
3. generate dataset.train, dataset.val in src/data directory with filename in train and val dataset. such that combining data_dir and filenames in should give the path to the files.
