### ISSUE TITLE
Nan output for demo and tracking

### ISSUE THREAD

**Issue by ZhangYuef** [ifzhang/FairMOT#467]
I test the demo part by:

>  python track.py mot --load_model ../models/crowdhuman_dla34.pth --conf_thres 0.6 --val_mot16 True --arch dla_34  --data_dir ../../dataset --data_cfg ../src/lib/cfg/mot17.json
or
> python demo.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.4

and got following warnings:

> No param reg.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param reg.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param reg.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param reg.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.

It seems I do not load the pretrained model correctly. I think I use the right parameter setting in the command line code. What should I do then?

**Comment by Gaoxinyue423** [comment]
I have the same problem. How did you solve it?

**Comment by ZhangYuef** [comment]
> I have the same problem. How did you solve it?

Not yet. It seems the problem is caused by the mismatch between model architecture and pretrained checkpoint.

 Maybe try the other pretrained model checkpoint or retrain your own model.

**Comment by Gaoxinyue423** [comment]
Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhang ***@***.***&gt;; 
发送时间: 2022年4月20日(星期三) 下午3:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ifzhang/FairMOT] Nan output for demo and tracking (Issue #467)





  
我也有同样的问题。  你是怎么解决的？ 
  
还没有。  似乎问题是由模型架构和预训练检查点之间的不匹配引起的。 
 
也许尝试其他预训练模型检查点或重新训练您自己的模型。 
 
— 
直接回复此邮件， 在 GitHub 上查看 ，或 退订 。 
您收到此消息是因为您发表了评论。 消息 ID： <ifzhang/FairMOT/issues/467/1103568345 @ github 。 com&gt;
