### ISSUE TITLE
gt files for MOT test data.

### ISSUE THREAD

**Issue by mahdiabdollahpour** [ifzhang/FairMOT#469]
Hi 

Thanks for the great repo and paper,
I downloaded MOT17 data from https://motchallenge.net/data/MOT17/
but it did not contain gt folders for test data. how can we have the gt folders to evaluate the models?
(I see you use test data gt folders in your code)

**Comment by HoYeolPark** [comment]
Hi, Can i know what to use gt folder?? if you keep me informed, Thanks for you!
