### ISSUE TITLE
Error While run sh MOT20_ft_mix_dla34

### ISSUE THREAD

**Issue by usmcseal911** [ifzhang/FairMOT#483]
I got this error
![image](https://user-images.githubusercontent.com/55080674/147255561-ebaa7f21-bf90-48ec-aaac-88449c83a49d.png)

is anyone got this error after did **sh mot20_ft_mix_dla34**? i tried to delete it then i got _file not found /mnt/d/data/yfzhang/MOT/JDE/MOT20/images/train/MOT20-05/img1/000181.jpg_ . I also tried to re-download the file and the result is still same. How to fix this issue?

**Comment by gmt710** [comment]
you need change tha data path to your own data path. ok?

**Comment by usmcseal911** [comment]
i did btw. Would u show me ur path to me? i changed in opts.py, gen_label_15.py, gen_label_20.py, track.py but still got 'file corrupt' warn.

This is gen_label_20.py path
![image](https://user-images.githubusercontent.com/55080674/147247989-a552c46e-a111-4b2b-abda-3ff2c7f0d37b.png)

This is gen_label15.py path
![image](https://user-images.githubusercontent.com/55080674/147248077-d6a9021f-cfeb-4448-893b-60d2c8585874.png)

**Comment by rainrae** [comment]
Hi, how did you solve the issue? I met a similar error when I changed the path following the direction. But the terminal said the file was not found. However, I could find the file in my directory.
![image](https://user-images.githubusercontent.com/89148747/204074933-79ea421e-b02d-4bd4-a278-8756eb3d0190.png)
