### ISSUE TITLE
Why can't get the MOT17_half MOTA paper provided

### ISSUE THREAD

**Issue by State226** [ifzhang/FairMOT#485]
Thanks for your great work.
![image](https://user-images.githubusercontent.com/67365385/147310447-0b1ba36d-7c9f-4dee-b8e0-b08d6956ed6c.png)
but I trained with your cfg, but I cant get the MOTA your paper provided,
only train on MOT17_half, I got 59.6,
train on CH+MOT17_half, I got 64,
I use training strategy in experiments/mot17_half_dla34.sh

**Comment by Wenbin94** [comment]
I have the same problem.only train on MOT17_half, I got 60.7

**Comment by State226** [comment]
I solve this problem ，I download the code again and follow the step to train ,use sh experiments/mot17_half_dla34.sh and no modify anything but data_dir

**Comment by State226** [comment]
> I have the same problem.only train on MOT17_half, I got 60.7

I solve this problem ，I download the code again and follow the step to train ,use sh experiments/mot17_half_dla34.sh and no modify anything but data_dir
