### ISSUE TITLE
您好 我想个初级的问题 这个dockerfile怎么用呀 开头的IMAGE_NAME 要传什么呢 什么也不写的的说非法过去不去呀

### ISSUE THREAD

**Issue by daixinguang** [ifzhang/FairMOT#507]
您好 我想个初级的问题 这个dockerfile怎么用呀 开头的IMAGE_NAME 要传什么呢 什么也不写的的说非法过去不去呀

_Originally posted by @fly2008begin in https://github.com/ifzhang/FairMOT/issues/267#issuecomment-766940594_

**Comment by liushuailiang** [comment]
ARG nvidia/cuda
FROM nvidia/cuda:10.2-runtime-ubuntu18.04

chinese help chinese
