### ISSUE TITLE
Is there a pretrained model for HRNet trained on crowdhuman dataset

### ISSUE THREAD

**Issue by kblittle** [ifzhang/FairMOT#513]
Hi, thanks for your awesome work. DLA pretrained model doesn't work well on my device . Can you provide a pre-trained model on crowdhuman dataset for HRNet?

**Comment by SmallGGgg** [comment]
> Hi, thanks for your awesome work. DLA pretrained model doesn't work well on my device . Can you provide a pre-trained model on crowdhuman dataset for HRNet?

I want one, too. Do you have it？

**Comment by richardvogg** [comment]
I would also be interested in the pre-trained weights for HRNet32. Are these easily available somewhere?
