### ISSUE TITLE
 Make a custom data set

### ISSUE THREAD

**Issue by tutu96177** [ifzhang/FairMOT#59]
Please consult the author. In the public mot dataset , "conf: this bbox contains the confidence degree of the object. It can be seen that it is not 0-1 in the traditional sense, and the higher the score is, the higher the confidence degree is."Or how do you make a custom data set? For example ,I want to track the car, How can I make the training datasets，how can I get the "conf "? thanks.

**Comment by ifzhang** [comment]
For training, we do not need the 'conf' parameter. The training datasets just need to contain the box, id and class label. You can follow issue #55 to train on a custom dataset.

**Comment by tutu96177** [comment]
Hi author , If I want to train a tracking sheep model, I only need to make a sheep data set similar to MOT20 data set format. Can I directly use FairMOT for training?

**Comment by CaptainEven** [comment]
@tutu96177 You can refer to https://github.com/CaptainEven/FairMOTVehicle
I have trained a network to track vehicles.
