### ISSUE TITLE
Can't download baseline model HRNetV2_W18 from Google link

### ISSUE THREAD

**Issue by trevorm7** [ifzhang/FairMOT#60]
The google link: https://drive.google.com/open?id=1Hna9jmA1jac42u8e9v6HXSS5aldV41YY
Says you need permission to download.

**Comment by ifzhang** [comment]
I have update the link and you can download it now!

**Comment by trevorm7** [comment]
Thanks!

**Comment by saikrithik** [comment]
Again, cant download the model, please help me out
