### ISSUE TITLE
Parameter --K

### ISSUE THREAD

**Issue by khodabakhshih** [ifzhang/FairMOT#61]
I try it with –K 500 but it causes to the following error:

2020-04-24 06:07:06 [INFO]: Processing frame 0 (100000.00 fps)
2020-04-24 06:07:06 [INFO]: boolean index did not match indexed array along dimension 0; dimension is 500 but corresponding boolean dimension is 128
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[image2 @ 0x55c2f8468000] Could find no file with path '../results/frame/%05d.jpg' and index in the range 0-4
../results/frame/%05d.jpg: No such file or directory

In fact for k>128 it causes to error. Would you please tell me how can I fix it.

**Comment by khodabakhshih** [comment]
it refers to "demo.py"

**Comment by ifzhang** [comment]
Thank you very much! I have fixed this bug. You can change the parameter -K now.

**Comment by khodabakhshih** [comment]
Thanks.
