### ISSUE TITLE
all_hrnet_v2_w18.pth

### ISSUE THREAD

**Issue by khodabakhshih** [ifzhang/FairMOT#63]
Thanks for your excellent work. I run the demo with model “all_dla34.pth” using the below script and all is ok.

python demo.py mot --load_model ../models/ all_dla34.pth --reid_dim 128 --conf_thres 0.4

but, when I use the model “all_hrnet_v2_w18.pth”  with the following commands using the model that you have recently uploaded.
python demo.py mot --load_model ../models/all_hrnet_v2_w18.pth --arch hrnet_18 --reid_dim 128 --conf_thres 0.4
i receive the following error:

Creating model...
2020-04-24 10:01:09 [INFO]: unexpected EOF, expected 6133124 more bytes. The file might be corrupted.
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f73cc075193 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x18cd59f (0x7f73cdd9559f in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: THStorage_free + 0x17 (0x7f73ce55dba7 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x55d65d (0x7f7416fc665d in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #4: python3() [0x54f6e6]
frame #5: python3() [0x5734e0]
frame #6: python3() [0x4b1a28]
frame #7: python3() [0x589078]
frame #8: python3() [0x5ade68]
frame #9: python3() [0x5ade7e]
frame #10: python3() [0x5ade7e]
frame #11: python3() [0x5ade7e]
frame #12: python3() [0x5ade7e]
frame #13: python3() [0x5ade7e]
frame #14: python3() [0x5ade7e]
frame #15: python3() [0x5ade7e]
frame #16: python3() [0x590669]
frame #17: python3() [0x590943]
<omitting python frames>
frame #19: python3() [0x509d48]
frame #20: python3() [0x50aa7d]
frame #22: python3() [0x508245]
frame #24: python3() [0x635222]
frame #29: __libc_start_main + 0xe7 (0x7f74310b8b97 in /lib/x86_64-linux-gnu/libc.so.6)

would you please tell me why?

**Comment by ifzhang** [comment]
The model may not be fully downloaded. I have uploaded the model again and you can download it again.

**Comment by khodabakhshih** [comment]
Thanks. I run it with the new model and the issue still exist. I think the problem is with the parameter “--arch hrnet_18”. Even  the model “all_dla34.pth” do not work with this parameter but work without it. When I run the model “” without parameter “--arch hrnet_18” as follows:

python demo.py mot --load_model ../models/all_hrnet_v2_w18.pth --reid_dim 128 --conf_thres 0.4

I received the warning as below. The code run but the output videos has no bboxes.

No param base.level4.tree2.tree2.conv1.weight. If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.

**Comment by CaptainEven** [comment]
I meet the same problem, even after i commented dcn in model.py, the info is as follows:
(FairMOT) jaya@jaya:/mnt/diskb/even/FairMOT/src$ python demo.py mot --load_model ../models/all_hrnet_v2_w18.pth --arch hrnet_18 --reid_dim 128 --conf_thres 0.4
Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /mnt/diskb/even/FairMOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 2, 'id': 128, 'reg': 2}
2020-04-27 16:32:26 [INFO]: Starting tracking...
Lenth of the video: 1500 frames
Creating model...
=> please download pre-trained models first!
2020-04-27 16:32:27 [INFO]: ../models/hrnetv2_w18_imagenet_pretrained.pth is not exist!
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[image2 @ 0x55bd929a7900] Could find no file with path '../results/frame/%05d.jpg' and index in the range 0-4
../results/frame/%05d.jpg: No such file or directory

**Comment by ifzhang** [comment]
The real error information is above the ffmpeg: '2020-04-27 16:32:27 [INFO]: ../models/hrnetv2_w18_imagenet_pretrained.pth is not exist!'. You need to first download the imagenet pretrained model and put it in the models directory. Or you can set pretrained=False of HRNet and do not load the imagenet pretrained model. Just loading my baseline model is OK.

**Comment by CaptainEven** [comment]
@ifzhang Thanks for answering, and, where to set pretrained=False of HRNet?

**Comment by ifzhang** [comment]
You can set PRETRAINED: '' here:
https://github.com/ifzhang/FairMOT/blob/81d8bb720e4115e2a8d2e8126007eb18d3354679/src/lib/models/networks/config/hrnet_w18.yaml#L31

**Comment by CaptainEven** [comment]
@ifzhang It works!

**Comment by mainguyenanhvu** [comment]
@ifzhang I set pretrained: False. However, it threw error:
ValueError: Type mismatch (<class 'str'> vs. <class 'bool'>) with values ( vs. False) for config key: MODEL.PRETRAINED

Please help me. Thank you.
