### ISSUE TITLE
Why the result video is 1920*1080？

### ISSUE THREAD

**Issue by texamc2** [ifzhang/FairMOT#66]
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv -
-enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb
--enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx
--enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp -
-enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx
 --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt

  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, image2, from 'E:/result/t10\frame/%05d.jpg':
Duration: 00:00:35.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn, 25 tbc
Please use -b:a or -b:v, -b is ambiguous
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mpeg4 (native))
Press [q] to stop, [?] for help
[swscaler @ 000002760db11100] deprecated pixel format used, make sure you did set range correctly
**The frame of result also is 1920*1080**
Thank you if you can help me.

**Comment by ifzhang** [comment]
I set it here:
https://github.com/ifzhang/FairMOT/blob/81d8bb720e4115e2a8d2e8126007eb18d3354679/src/lib/datasets/dataset/jde.py#L97
You can change it here. But sometimes I use other resolutions and the mp4 file cannot be played. So I set 1920 * 1080.

**Comment by texamc2** [comment]
> I set it here:
> https://github.com/ifzhang/FairMOT/blob/81d8bb720e4115e2a8d2e8126007eb18d3354679/src/lib/datasets/dataset/jde.py#L97
> 
> 
> You can change it here. But sometimes I use other resolutions and the mp4 file cannot be played. So I set 1920 * 1080.

Thank you very much!

**Comment by texamc2** [comment]
> 我在这里设置：
> https://github.com/ifzhang/FairMOT/blob/81d8bb720e4115e2a8d2e8126007eb18d3354679/src/lib/datasets/dataset/jde.py#L97
> 
> 
> 您可以在这里更改。但是有时我使用其他分辨率，无法播放mp4文件。所以我设定为1920 * 1080。

Excuse me. When i run demo.py,first frame has no result? it begins in second frame .what should i do? In first frame ,i hope it has result.
2,1,773.7603225197818,341.44530029296874,99.0716645307489,286.45635986328125,0.9027215838432312,0
2,2,857.6210584685496,291.3268676757813,113.8205173402446,325.06212158203124,0.8994327187538147,0
2,3,971.2500636673867,335.5344665527344,124.06793907147673,315.54619750976565,0.9066966772079468,0
2,4,593.2579420569053,593.7679687499999,134.1047579760331,363.8332275390625,0.8693252801895142,0
2,5,902.1541617197139,-4.0293968677520695,70.14524101369712,191.55421447753906,0.8806121945381165,0

**Comment by texamc2** [comment]
> > 我在这里设置：
> > https://github.com/ifzhang/FairMOT/blob/81d8bb720e4115e2a8d2e8126007eb18d3354679/src/lib/datasets/dataset/jde.py#L97
> > 
> > 您可以在这里更改。但是有时我使用其他分辨率，无法播放mp4文件。所以我设定为1920 * 1080。
> 
> 劳驾。当我运行demo.py时，第一帧没有结果吗？它从第二帧开始。我该怎么办？在第一帧中，我希望它能有结果。
> 2,1,773.7603225197818,341.44530029296874,99.0716645307489,286.45635986328125,0.9027215838432312,0
> 2,2,857.6210584685496,291.3268676757813,113.8205173402446,325.06212158203124,0.8994327187538147,0
> 2,3,971.2500636673867,335.5344665527344,124.06793907147673,315.54619750976565,0.9066966772079468,0
> 2,4,593.2579420569053,593.7679687499999,134.1047579760331,363.8332275390625,0.8693252801895142 ，0
> 2,5,902.1541617197139，-4.0293968677520695,70.14524101369712,191.55421447753906,0.8806121945381165,0

[(1, [], [], [])]
[(1, [], [], []), (2, [array([     773.76,      341.45,      99.072,      286.46]), array([     857.62,      291.33,      113.82,      325.06]), ar
ray([     971.25,      335.53,      124.07,      315.55]), array([     593.26,      593.77,       134.1,      363.83]), array([     902.15,     -4.
0294,      70.145,      191.55]), array([     844.27,     -0.1079,      65.185,      182.18]), array([      469.6,      543.42,      130.16,      3
97.27]), array([     1528.6,       89.97,      65.225,      173.02]), array([     1427.1,      66.539,      73.197,      186.75]), array([       16
82,      97.133,      84.329,      196.41])], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [0.9027216, 0.8994327, 0.9066967, 0.8693253, 0.8806122, 0.82773393,
0.7837238, 0.5454654, 0.5844325, 0.4606995])]

**Comment by typhoonlee** [comment]
Did you solve this problem? I also encountered this problem
