### ISSUE TITLE
Meet some difficulties in training steps

### ISSUE THREAD

**Issue by dongziqi001** [ifzhang/FairMOT#67]
I followed the instruction you provided.
"Change the dataset root directory 'root' in src/lib/cfg/data.json and 'data_dir' in src/lib/opts.py"

I put my dataset in FairMOT-master,named CUHK-SYSU. The same directory as models/src...
Then I changed   'root' in src/lib/cfg/data.json.
{
    "root":"../CUHK-SYSU",
    "train":
    {
        "cuhksysu":"./data/cuhksysu.train"
    },
    "test_emb":
    {
        "cuhksysu":"./data/cuhksysu.val"
    },
    "test":
    {
        "cuhksysu":"./data/cuhksysu.val"
    }
}
 ---------------------------------------------------------------------
OSError: ../CUHK-SYSU\CUHKSYSU/labels_with_ids/s10000.txt not found.

I guess I did something wrong in this step. 
Then I tried  "root":"F:/study/FairMOT-master/FairMOT-master/CUHK-SYSU", and  "root":"../../CUHK-SYSU",
BUT all showed the same error.
Can you help me to solve this problem??Thanks!!!

**Comment by ifzhang** [comment]
You may check the directory of your dataset and the directorys in cuhksysu.train file. Make sure that they match.
