### ISSUE TITLE
make DCNV2 error

### ISSUE THREAD

**Issue by CaptainEven** [ifzhang/FairMOT#69]
CUDA 10.2 and gcc 7.5
/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(86): error: identifier "THCState_getCurrentStream" is undefined

/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(182): error: identifier "THCState_getCurrentStream" is undefined

**Comment by duanzhiihao** [comment]
I met the same problem using Ubuntu 20.04, GCC 9.3, cuda10.1, python 3.7, and pytorch=1.5. I solved it by downgrading PyTorch to 1.4.

**Comment by CaptainEven** [comment]
@duanzhiihao Thanks for replying!
