### ISSUE TITLE
No module named 'cython_bbox'

### ISSUE THREAD

**Issue by dongziqi001** [ifzhang/FairMOT#8]
After run python setup.py build develop, It shows:
正在生成代码
已完成代码的生成
running develop
running egg_info
creating DCNv2.egg-info
writing DCNv2.egg-info\PKG-INFO
writing dependency_links to DCNv2.egg-info\dependency_links.txt
writing top-level names to DCNv2.egg-info\top_level.txt
writing manifest file 'DCNv2.egg-info\SOURCES.txt'
reading manifest file 'DCNv2.egg-info\SOURCES.txt'
writing manifest file 'DCNv2.egg-info\SOURCES.txt'
running build_ext
copying build\lib.win-amd64-3.7\_ext.cp37-win_amd64.pyd ->
Creating c:\users\dongziqi\anaconda3\envs\fairmot\lib\site-packages\DCNv2.egg-link (link to .)
Adding DCNv2 0.1 to easy-install.pth file

Installed f:\study\fairmot-master\fairmot-master\src\lib\models\networks\dcnv2
Processing dependencies for DCNv2==0.1
Finished processing dependencies for DCNv2==0.1

this is the first build step, I have no idea whether it is success or not.
But it generate _ext.cp37-win_amd64.pyd.
=================================================================And then I run:python demo.py mot --load_model ../models/all_dla34.pth
It shows:
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    import datasets.dataset.jde as datasets
  File "F:\study\FairMOT-master\FairMOT-master\src\lib\datasets\dataset\jde.py", line 16, in <module>
    from cython_bbox import bbox_overlaps as bbox_ious
ModuleNotFoundError: No module named 'cython_bbox'
=================================================================
Then I tried: pip install cython_bbox, However, also failed.
Failed to build cython-bbox
Installing collected packages: cython-bbox
    Running setup.py install for cython-bbox ... error
=================================================================
I dont know which step is wrong. Do i failed in the first build step???
Thank you for you answer!!!

**Comment by zubairahmed-ai** [comment]
Little bit ahead of you see my issue https://github.com/ifzhang/FairMOT/issues/5 
I made some notes during install, here's how to fix cython-bbox will fail to install on Windows, follow the steps in this and my comment in the post  https://stackoverflow.com/questions/60349980/is-there-a-way-to-install-cython-bbox-for-windows

**Comment by dongziqi001** [comment]
It works!!!Thank you!!! You are so great!!Bobobo~

**Comment by zubairahmed-ai** [comment]
Nice if you can check my issue https://github.com/ifzhang/FairMOT/issues/5 and let me know if you ran into it and fixed it, it'll be great

**Comment by KevenLee** [comment]
you should just enter "pip install cython_bbox"
