### ISSUE TITLE
make.sh

### ISSUE THREAD

**Issue by khodabakhshih** [ifzhang/FairMOT#86]
Thanks for sharing your codes. Last week I run the code without any problem in google colab. Today, I try to run the make.sh and receive the following error:

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_cpu.cpp -o build/temp.linux-x86_64-3.6/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu -o build/temp.linux-x86_64-3.6/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=sm_60 -std=c++14
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu -o build/temp.linux-x86_64-3.6/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=sm_60 -std=c++14
/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(86): error: identifier "THCState_getCurrentStream" is undefined

/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(182): error: identifier "THCState_getCurrentStream" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00000192_00000000-6_dcn_v2_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

would you please tell me the issue?

**Comment by khodabakhshih** [comment]
The error was with the version of torch and torch vision. I rolled back to torch 1.4.0 and torchvision 0.5.0 and solved the issue. 
Please correct the expression "Install dependencies. We use python 3.7 and pytorch >= 1.2.0" on the Readme.md file

**Comment by xinyuanqian** [comment]
hi, 

> The error was with the version of torch and torch vision. I rolled back to torch 1.4.0 and torchvision 0.5.0 and solved the issue.
> Please correct the expression "Install dependencies. We use python 3.7 and pytorch >= 1.2.0" on the Readme.md file

Hi, how could you identify which torch and torchvision to install? by trying?

**Comment by khodabakhshih** [comment]
I work by google colab. Its packages including torch and torchvision is automatically updated over the time. One day i noticed that the ipynb file did not run. I checked it and finally i realized that its due to the torch version updating.

**Comment by mainguyenanhvu** [comment]
> I work by google colab. Its packages including torch and torchvision is automatically updated over the time. One day i noticed that the ipynb file did not run. I checked it and finally i realized that its due to the torch version updating.
Could you show me the way to fix these errors? I have faced with them. Thank you very much.

**Comment by Panczo** [comment]
Unfortunately I get the same error even when I use torchivision 0.5.0 and torch 1.4.0.
Is someone able to tell me what else can I do to run FairMOT on google colab?

**Comment by khodabakhshih** [comment]
@Panczo here is what i write in colab cells:
 !pip install torch==1.4 torchvision==0.5

%cd '/content/drive/My Drive/Colab Notebooks/FairMOT'
!pip install -r requirements.txt

%rm -rf '/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/DCNv2.egg-info'
%rm -rf '/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/build'

%cd /content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2 
!sh make.sh

%rm -rf '/content/drive/My Drive/Colab Notebooks/FairMOT/results'
%cd '/content/drive/My Drive/Colab Notebooks/FairMOT/src'

!python demo.py mot --load_model ../models/all_dla34.pth

**Comment by Reagan1947** [comment]
> @Panczo here is what i write in colab cells:
> !pip install torch==1.4 torchvision==0.5
> 
> %cd '/content/drive/My Drive/Colab Notebooks/FairMOT'
> !pip install -r requirements.txt
> 
> %rm -rf '/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/DCNv2.egg-info'
> %rm -rf '/content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2/build'
> 
> %cd /content/drive/My Drive/Colab Notebooks/FairMOT/src/lib/models/networks/DCNv2
> !sh make.sh
> 
> %rm -rf '/content/drive/My Drive/Colab Notebooks/FairMOT/results'
> %cd '/content/drive/My Drive/Colab Notebooks/FairMOT/src'
> 
> !python demo.py mot --load_model ../models/all_dla34.pth

Could you Share your colab notebook? Thank so much!!
