### ISSUE TITLE
Original Centernet has normalization for input image

### ISSUE THREAD

**Issue by jackie840129** [ifzhang/FairMOT#87]
Hi,
The pretrained model "ctdet_coco_dla_2x" is trained with input normalized by mean and std.
But the data preprocessing in your code, the image is only /=255. 
Did you try to normalize the input image?
If the input was not normalized, is it weird to load the pretrained model?

Thanks!

**Comment by ifzhang** [comment]
Yes! That's a problem. To make it the same may get better results. Thanks~

**Comment by jackie840129** [comment]
OK  Thanks~

**Comment by nmll** [comment]
Hello! I also want to ask about that the image is only /=255 instead of with input normalized by mean and std is designed for ReID?
