### ISSUE TITLE
 Multi-class multi-object tracking

### ISSUE THREAD

**Issue by rose-jinyang** [ifzhang/FairMOT#89]
Hello
How are you?
Thanks for contributing this great paper and code.
I have a question.
How do you think about multi-class multi-object tracking?
I think that there is this problem in real world.
For example, if we are going to track vehicles and persons at the same time ...
Is it possible to implement multi-class multi-object tracking on your system?
Thanks

**Comment by ifzhang** [comment]
Yes, you can just set the channel of the hm head. Now it is 1 and it can be set 2, 3, 4... depending on your class. Then, you can use the multi-class dataset to train the model.

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.

**Comment by rose-jinyang** [comment]
Hello
how are you?
I have more questions in implementing multi-class MOT.
![image](https://user-images.githubusercontent.com/47862419/81506769-46449d00-932b-11ea-8267-ab5fd5ba33ee.png)
![image](https://user-images.githubusercontent.com/47862419/81506871-ebf80c00-932b-11ea-8e8d-a806923c7b47.png)
In the above code, I found that dataset.num_classes is the number of classes to train.
When I set opt.heads in the function _update_dataset_info_and_set_heads_, I'm confused in setting opt.heads['wh'].
When opt.num_classes > 1, if the above code is right, should I enumerate the parameter _cat_spec_wh_ in command line option.
Thanks

**Comment by tiberium24** [comment]
I have the same question! Any updates? @ifzhang

**Comment by yaoshanliang** [comment]
> I have the same question! Any updates? @ifzhang

No updates.
