### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by rose-jinyang** [ifzhang/FairMOT#91]
Hi @ifzhang
How are you?
Excuse me, do you know that the latest DCNv2 supports the building on CPU?
if so, could you replace DCNv2 module to the latest so that your project can run on CPU/GPU without any restriction?
Thanks

**Comment by ifzhang** [comment]
It seems that the latest DCNv2 supports CPU now: https://github.com/CharlesShang/DCNv2
I will update it later.

**Comment by rose-jinyang** [comment]
Thanks for your reply.
Well, excuse me, can we communicate on WeChat?
if you agree, please ping me.
ID: jin19856152013423
Thanks
