### ISSUE TITLE
About re-id training

### ISSUE THREAD

**Issue by CaptainEven** [ifzhang/FairMOT#96]
Dear author,
    I found the last layer of the re-id training part is a FC layer, if there is a huge amount of track ids(e.g 1000 000 ids) for training, then the parameter amount and GPU memory consumption is huge too, as a result, the training is almost impossible, how to solve the problem like this?

**Comment by ifzhang** [comment]
Yes, that's a problem. If the GPU consumption is too large, we can fix the parameters of the FC layer and the results are still good. Triplet loss may prevent this problem, but the performance may not be as good as CE loss.

**Comment by CaptainEven** [comment]
@ifzhang Thanks for your explanation and solution! I 'll have a try.

**Comment by CaptainEven** [comment]
@ifzhang Thanks for your suggestion! When i start to consider the details of your suggestion, i found two problems: 1. If we fix the size of FC's out dim, 2000 for example, but the actual track ids need to be classified is 5000, then an out of range access may occur when conduct EC loss calculation; 2. the triplet loss calculation need a triplet of feature vector as input, how to meet this need in a single image?

**Comment by ifzhang** [comment]
1. We do not train the parameter of the FC layer. The out_dim of FC should still be the total id number. 2. If you want to use triplet loss, you need to sample the training images and make sure there are persons of the same id in a training batch. 
In fact I think the number of ids < 100000 are acceptable using CE loss. If the ids really > 1000000, there should be really large training data and the training may take a long time and seems impossible.
